import re

def translate_file(filepath, replacements):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    original = content
    for korean, english in replacements:
        content = content.replace(korean, english)
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False

BASE = '/home/youngho/workspace/loitering_tracking'

# ============================================================
# RFP_Dashboard_Layout.md
# ============================================================
layout_replacements = [
    # Title and metadata
    ('# RFP: Dashboard 전체 화면 레이아웃 및 구성', '# RFP: Dashboard Full-Screen Layout and Configuration'),
    ('**Status**: Phase-2 다중 화면 레이아웃 구현 반영', '**Status**: Phase-2 multi-screen layout implementation reflected'),

    # Table of contents
    ('## 목차', '## Table of Contents'),
    ('1. [개요](#1-개요)', '1. [Overview](#1-overview)'),
    ('2. [전체 화면 구성도](#2-전체-화면-구성도)', '2. [Full Screen Layout Diagram](#2-full-screen-layout-diagram)'),
    ('3. [Top Bar (헤더)](#3-top-bar-헤더)', '3. [Top Bar (Header)](#3-top-bar-header)'),
    ('4. [Camera Grid (메인 영역)](#4-camera-grid-메인-영역)', '4. [Camera Grid (Main Area)](#4-camera-grid-main-area)'),
    ('   - 4.1 다중 화면 레이아웃 정의', '   - 4.1 Multi-screen layout definition'),
    ('   - 4.2 Equal Grid 렌더링', '   - 4.2 Equal Grid rendering'),
    ('   - 4.3 Featured (1 Main + Sub) 렌더링', '   - 4.3 Featured (1 Main + Sub) rendering'),
    ('   - 4.4 LayoutPicker 드롭다운', '   - 4.4 LayoutPicker dropdown'),
    ('   - 4.5 카메라 셀 동작', '   - 4.5 Camera cell behavior'),
    ('   - 4.6 Compact 모드', '   - 4.6 Compact mode'),
    ('   - 4.7 Discovered Camera Panel', '   - 4.7 Discovered Camera Panel'),
    ('5. [Sidebar (우측 패널)](#5-sidebar-우측-패널)', '5. [Sidebar (Right Panel)](#5-sidebar-right-panel)'),
    ('6. [Fullscreen Overlay](#6-fullscreen-overlay)', '6. [Fullscreen Overlay](#6-fullscreen-overlay)'),
    ('7. [Settings Modal](#7-settings-modal)', '7. [Settings Modal](#7-settings-modal)'),
    ('8. [반응형 및 레이아웃 제약](#8-반응형-및-레이아웃-제약)', '8. [Responsive & Layout Constraints](#8-responsive--layout-constraints)'),
    ('9. [국제화(i18n) 지원](#9-국제화i18n-지원)', '9. [Internationalization (i18n) Support](#9-internationalization-i18n-support)'),
    ('10. [상태 관리 구조](#10-상태-관리-구조)', '10. [State Management Structure](#10-state-management-structure)'),
    ('11. [구현 현황](#11-구현-현황)', '11. [Implementation Status](#11-implementation-status)'),

    # Section 1
    ('## 1. 개요', '## 1. Overview'),
    ('### 1.1 목적\n\n본 문서는 Loitering Detection & Tracking System (LTS)의 **Dashboard 전체 화면 레이아웃**에 대한 기술 요구사항을 정의한다. 운영자가 실시간으로 다수의 카메라 피드를 감시하고, 경보를 확인하며, 구역(Zone)을 관리할 수 있는 단일 페이지 대시보드 인터페이스를 대상으로 한다.',
     '### 1.1 Purpose\n\nThis document defines the technical requirements for the **Dashboard full-screen layout** of the Loitering Detection & Tracking System (LTS). It targets the single-page dashboard interface that allows operators to monitor multiple camera feeds in real time, review alerts, and manage zones.'),
    ('### 1.2 범위\n\n- 전체 화면 영역 분할 (Header / Camera Grid / Sidebar)\n- Top Bar 구성 요소 및 동작 사양\n- Camera Grid 레이아웃 전환 (1 / 4 / 9 / 16 분할)\n- Sidebar 탭 구조 (Cameras / Alerts / Zones)\n- 전체화면(Fullscreen) 오버레이 진입/복귀\n- 설정(Settings) Modal 진입\n- 다국어(i18n) UI 텍스트 처리',
     '### 1.2 Scope\n\n- Full screen area division (Header / Camera Grid / Sidebar)\n- Top Bar component and behavior specification\n- Camera Grid layout switching (1 / 4 / 9 / 16 split)\n- Sidebar tab structure (Cameras / Alerts / Zones)\n- Fullscreen overlay entry/exit\n- Settings Modal entry\n- Multilingual (i18n) UI text handling'),

    # Section 2
    ('## 2. 전체 화면 구성도', '## 2. Full Screen Layout Diagram'),
    ('### 2.1 레이아웃 구조 (ASCII)', '### 2.1 Layout Structure (ASCII)'),
    ('│  [LTS]  Loitering Tracking System   ●LIVE   0/1 live  [레이아웃▼]  [⚙]   │',
     '│  [LTS]  Loitering Tracking System   ●LIVE   0/1 live  [Layout▼]  [⚙]   │'),
    ('### 2.2 주요 영역 치수', '### 2.2 Key Area Dimensions'),
    ('| 영역 | 너비 | 높이 | CSS 클래스 |', '| Area | Width | Height | CSS Class |'),
    ('| 전체 앱 컨테이너 | 100vw | 100vh | `flex flex-col h-screen overflow-hidden` |',
     '| Full app container | 100vw | 100vh | `flex flex-col h-screen overflow-hidden` |'),
    ('| Top Bar | 100% | `auto` (≈40px) | `flex-shrink-0` |', '| Top Bar | 100% | `auto` (≈40px) | `flex-shrink-0` |'),
    ('| Content Row | 100% | 나머지 전체 | `flex flex-1 overflow-hidden` |',
     '| Content Row | 100% | Remaining | `flex flex-1 overflow-hidden` |'),
    ('| Camera Grid (main) | 나머지 | 100% | `flex-1 overflow-hidden p-2` |',
     '| Camera Grid (main) | Remaining | 100% | `flex-1 overflow-hidden p-2` |'),
    ('| Sidebar | 288px 고정 | 100% | `w-72 flex-shrink-0` |', '| Sidebar | 288px fixed | 100% | `w-72 flex-shrink-0` |'),
    ('### 2.3 색상 테마\n\n전체 UI는 다크 테마를 기본으로 한다.',
     '### 2.3 Color Theme\n\nThe entire UI uses a dark theme by default.'),
    ('| 영역 | 배경색 | 테두리 |', '| Area | Background | Border |'),
    ('| 전체 앱 배경 | `bg-gray-900` (#111827) | — |', '| Full app background | `bg-gray-900` (#111827) | — |'),
    ('| Top Bar, Sidebar | `bg-gray-800` (#1F2937) | `border-gray-700` (#374151) |',
     '| Top Bar, Sidebar | `bg-gray-800` (#1F2937) | `border-gray-700` (#374151) |'),
    ('| 카메라 셀 (빈 칸) | `bg-gray-800` (#1F2937) | — |', '| Camera cell (empty) | `bg-gray-800` (#1F2937) | — |'),
    ('| 카메라 셀 (영상) | `bg-gray-900` (#111827) | — |', '| Camera cell (video) | `bg-gray-900` (#111827) | — |'),
    ('| 선택된 카메라 셀 | — | `ring-2 ring-blue-500` |', '| Selected camera cell | — | `ring-2 ring-blue-500` |'),

    # Section 3
    ('## 3. Top Bar (헤더)', '## 3. Top Bar (Header)'),
    ('### 3.1 구성 요소 (좌→우 순서)', '### 3.1 Components (left→right order)'),
    ('```\n[로고] [앱 제목]   [연결 상태]   ────────────   [카메라 수] [레이아웃] [설정]\n```',
     '```\n[Logo] [App Title]   [Connection Status]   ────────────   [Camera Count] [Layout] [Settings]\n```'),
    ('| 요소 | 설명 | 구현 |', '| Element | Description | Implementation |'),
    ('| **로고 뱃지** | `LTS` 텍스트, `bg-blue-600` 6×6 아이콘 | `w-6 h-6 bg-blue-600 rounded` |',
     '| **Logo badge** | `LTS` text, `bg-blue-600` 6×6 icon | `w-6 h-6 bg-blue-600 rounded` |'),
    ('| **앱 제목** | 다국어 `appTitle` 키 | `text-sm font-bold text-white` |',
     '| **App title** | i18n `appTitle` key | `text-sm font-bold text-white` |'),
    ('| **연결 상태** | Socket.IO 연결 여부 — 녹색 펄스(●LIVE) / 빨간(●DISC) | `w-2.5 h-2.5 rounded-full animate-pulse` |',
     '| **Connection status** | Socket.IO connection — green pulse (●LIVE) / red (●DISC) | `w-2.5 h-2.5 rounded-full animate-pulse` |'),
    ('| **Spacer** | 남은 공간 채움 | `flex-1` |', '| **Spacer** | Fills remaining space | `flex-1` |'),
    ('| **카메라 카운트** | `{live}/{total} LIVE` 형식 | `text-xs text-gray-400` |',
     '| **Camera count** | `{live}/{total} LIVE` format | `text-xs text-gray-400` |'),
    ('| **레이아웃 피커** | 드롭다운 버튼 → 16종 레이아웃 선택 | `LayoutPicker` 컴포넌트 |',
     '| **Layout picker** | Dropdown button → select from 16 layouts | `LayoutPicker` component |'),
    ('| **설정 아이콘** | 톱니바퀴 SVG → SettingsModal 열기 | `hover:bg-gray-700` |',
     '| **Settings icon** | Gear SVG → opens SettingsModal | `hover:bg-gray-700` |'),
    ('### 3.2 연결 상태 표시 사양', '### 3.2 Connection Status Display Specification'),
    ('| 상태 | 색상 | 애니메이션 | 텍스트 |', '| State | Color | Animation | Text |'),
    ('| Connected | `bg-green-500` | `animate-pulse` | i18n `connected` |',
     '| Connected | `bg-green-500` | `animate-pulse` | i18n `connected` |'),
    ('| Disconnected | `bg-red-500` | 없음 | i18n `disconnected` |',
     '| Disconnected | `bg-red-500` | None | i18n `disconnected` |'),
    ('### 3.3 레이아웃 피커 (LayoutPicker)', '### 3.3 Layout Picker (LayoutPicker)'),
    ('- 현재 선택된 레이아웃을 SVG 아이콘 + 라벨로 표시하는 **드롭다운 버튼**',
     '- A **dropdown button** that displays the currently selected layout as SVG icon + label'),
    ('- 클릭 시 `w-72` 드롭다운 패널 열림; 바깥 영역 클릭 시 닫힘',
     '- Click opens `w-72` dropdown panel; clicking outside closes it'),
    ('- 드롭다운 패널 내부 구성:', '- Dropdown panel internal structure:'),
    ('- 각 레이아웃 버튼: SVG 미니 아이콘(20×20) + 레이아웃 ID 라벨 (`text-[9px]`)',
     '- Each layout button: SVG mini icon (20×20) + layout ID label (`text-[9px]`)'),
    ('- 활성 레이아웃: `bg-blue-600 text-white`', '- Active layout: `bg-blue-600 text-white`'),
    ('- 비활성: `bg-gray-700 text-gray-300 hover:bg-gray-600`',
     '- Inactive: `bg-gray-700 text-gray-300 hover:bg-gray-600`'),
    ('- `LayoutIcon` 컴포넌트: 각 레이아웃을 SVG 격자/분할로 시각화',
     '- `LayoutIcon` component: visualizes each layout as SVG grid/split'),

    # Section 4
    ('## 4. Camera Grid (메인 영역)', '## 4. Camera Grid (Main Area)'),
    ('### 4.1 다중 화면 레이아웃 정의', '### 4.1 Multi-Screen Layout Definition'),
    ('`CameraGrid` 컴포넌트는 16종 레이아웃을 지원한다. 레이아웃은 두 가지 유형으로 구분된다.',
     'The `CameraGrid` component supports 16 layouts. Layouts are divided into two types.'),
    ('#### 4.1.1 레이아웃 타입 (LayoutId)', '#### 4.1.1 Layout Type (LayoutId)'),
    ('#### 4.1.2 Equal Grid 레이아웃', '#### 4.1.2 Equal Grid Layout'),
    ('균등 격자 — 모든 셀의 크기가 동일하다.', 'Equal grid — all cells are the same size.'),
    ('| LayoutId | 채널 수 | 그리드 | 셀 수 | 빈 셀 |', '| LayoutId | Channels | Grid | Cells | Empty Cells |'),
    ('| `5`  | 5  | 3×2 | 6  | 1 (마지막) |', '| `5`  | 5  | 3×2 | 6  | 1 (last) |'),
    ('#### 4.1.3 Featured (1 Main + Sub) 레이아웃', '#### 4.1.3 Featured (1 Main + Sub) Layout'),
    ('왼쪽에 1개 메인 카메라(대형), 오른쪽에 N개 서브 카메라(소형 격자)를 배치한다.',
     'Places 1 main camera (large) on the left and N sub cameras (small grid) on the right.'),
    ('| LayoutId | 채널 수 | 메인 비율 | 서브 열 수 | 서브 행 수 |',
     '| LayoutId | Channels | Main ratio | Sub columns | Sub rows |'),
    ('### 4.2 Equal Grid 렌더링', '### 4.2 Equal Grid Rendering'),
    ('- 컨테이너: `w-full h-full` — 메인 영역을 100% 채움',
     '- Container: `w-full h-full` — fills the main area 100%'),
    ('- 각 셀은 `aspect-video` 없음 — 행이 나눠진 비율로 자동 높이 결정',
     '- Each cell has no `aspect-video` — height auto-determined by row ratio'),
    ('- `gridTemplateRows`를 명시하여 전체 높이를 균등 분배',
     '- Specify `gridTemplateRows` for even height distribution'),
    ('### 4.3 Featured (1 Main + Sub) 렌더링', '### 4.3 Featured (1 Main + Sub) Rendering'),
    ('  ┌─── 메인 셀 (flex: mainFlex) ──────┬── 서브 패널 (flex: subFlex) ──┐',
     '  ┌─── Main cell (flex: mainFlex) ────┬── Sub panel (flex: subFlex) ──┐'),
    ('  │   CameraCell (cameras[0])        │  display:grid                 │',
     '  │   CameraCell (cameras[0])        │  display:grid                 │'),
    ('  │                                  │  cameras[1..N]                │',
     '  │                                  │  cameras[1..N]                │'),
    ('- `flex: mainFlex` / `flex: subFlex` 인라인 스타일로 비율 제어',
     '- Ratio controlled via `flex: mainFlex` / `flex: subFlex` inline styles'),
    ('- 메인 셀은 항상 `compact=false` (카메라 이름 표시)',
     '- Main cell always has `compact=false` (shows camera name)'),
    ('- 서브 셀은 subCount > 7 이면 `compact=true`',
     '- Sub cells have `compact=true` when subCount > 7'),
    ('### 4.4 LayoutPicker 드롭다운', '### 4.4 LayoutPicker Dropdown'),
    ('→ §3.3 참조', '→ See §3.3'),
    ('### 4.5 카메라 셀 동작', '### 4.5 Camera Cell Behavior'),
    ('| 이벤트 | 동작 |', '| Event | Behavior |'),
    ('| **더블 클릭** | Fullscreen Overlay 전환 |', '| **Double click** | Switch to Fullscreen Overlay |'),
    ('| **선택됨** | `ring-2 ring-blue-500 ring-offset-1 ring-offset-gray-900` |',
     '| **Selected** | `ring-2 ring-blue-500 ring-offset-1 ring-offset-gray-900` |'),
    ('| 카메라 타입 | 특이 표시 |', '| Camera type | Special display |'),
    ('| YouTube 가상 채널 | 우상단 `YT` 빨간 뱃지 |', '| YouTube virtual channel | `YT` red badge in top-right |'),
    ('| YouTube + status=error | 검정 오버레이 + "⚠ 오류" + 재시작 버튼 (compact 모드에서 버튼 숨김) |',
     '| YouTube + status=error | Black overlay + "⚠ Error" + restart button (button hidden in compact mode) |'),
    ('| 등록 안 된 빈 셀 | 회색 배경 + 슬롯 번호 (compact 모드에서 번호 숨김) |',
     '| Unregistered empty cell | Gray background + slot number (number hidden in compact mode) |'),
    ('### 4.6 Compact 모드', '### 4.6 Compact Mode'),
    ('채널 수 ≥ 16이면 compact 모드가 활성화된다.', 'Compact mode is activated when channel count ≥ 16.'),
    ('| 요소 | 일반 모드 | Compact 모드 |', '| Element | Normal mode | Compact mode |'),
    ('| 카메라 이름 라벨 | 셀 하단 그라디언트 + 이름 | **숨김** |',
     '| Camera name label | Cell bottom gradient + name | **Hidden** |'),
    ('| 채널 인덱스 | 숨김 | 좌상단 소형 칩 (7px 폰트) |',
     '| Channel index | Hidden | Small chip in top-left (7px font) |'),
    ('| 빈 셀 슬롯 번호 | 중앙 표시 | **숨김** |', '| Empty cell slot number | Center display | **Hidden** |'),
    ('| YouTube 재시작 버튼 | 표시 | **숨김** |', '| YouTube restart button | Shown | **Hidden** |'),
    ('### 4.7 Discovered Camera Panel', '### 4.7 Discovered Camera Panel'),
    ('ONVIF/UDP 탐색으로 발견된 카메라를 선택했을 때 메인 영역 위에 오버레이로 표시된다.',
     'Displayed as an overlay above the main area when a camera discovered via ONVIF/UDP is selected.'),
    ('- 컴포넌트: `DiscoveredCameraPanel`', '- Component: `DiscoveredCameraPanel`'),
    ('- 위치: `absolute` (Camera Grid 기준)', '- Position: `absolute` (relative to Camera Grid)'),
    ('- 닫기: DiscoveryStore의 `select(null)` 호출', '- Close: calls `select(null)` on DiscoveryStore'),

    # Section 5
    ('## 5. Sidebar (우측 패널)', '## 5. Sidebar (Right Panel)'),
    ('### 5.1 구조', '### 5.1 Structure'),
    ('│  [CAMERAS] [ALERTS] [ZONES]  │  ← 탭 바 (flex, border-b)',
     '│  [CAMERAS] [ALERTS] [ZONES]  │  ← Tab bar (flex, border-b)'),
    ('│      Active Tab Content      │  ← flex-1, overflow-hidden',
     '│      Active Tab Content      │  ← flex-1, overflow-hidden'),
    ('- 너비: `w-72` (288px) 고정', '- Width: `w-72` (288px) fixed'),
    ('- 배경: `bg-gray-800`', '- Background: `bg-gray-800`'),
    ('- 구분선: `border-l border-gray-700`', '- Divider: `border-l border-gray-700`'),
    ('### 5.2 탭 버튼 사양', '### 5.2 Tab Button Specification'),
    ('| 탭 ID | 표시 텍스트 | i18n 키 | 배지 |', '| Tab ID | Display Text | i18n Key | Badge |'),
    ('| `cameras` | CAMERAS | `tabCameras` | 없음 |', '| `cameras` | CAMERAS | `tabCameras` | None |'),
    ('| `alerts` | ALERTS | `tabAlerts` | 미확인 수 (빨간 원) |',
     '| `alerts` | ALERTS | `tabAlerts` | Unacknowledged count (red circle) |'),
    ('| `zones` | ZONES | `tabZones` | 없음 |', '| `zones` | ZONES | `tabZones` | None |'),
    ('**활성 탭**: `text-blue-400 border-b-2 border-blue-400`', '**Active tab**: `text-blue-400 border-b-2 border-blue-400`'),
    ('**비활성 탭**: `text-gray-500 hover:text-gray-300`', '**Inactive tab**: `text-gray-500 hover:text-gray-300`'),
    ('**Alerts 배지**: 미확인(unacknowledged) 경보가 1개 이상이면 탭 우상단에 빨간 원 배지 표시',
     '**Alerts badge**: If there are 1 or more unacknowledged alerts, a red circle badge is displayed in the top-right of the tab'),
    ('- 9개 이하: 숫자 표시', '- 9 or fewer: shows number'),
    ('- 10개 이상: `9+` 표시', '- 10 or more: shows `9+`'),
    ('### 5.3 각 탭 컨텐츠 컴포넌트', '### 5.3 Tab Content Components'),
    ('| 탭 | 컴포넌트 | 참조 RFP |', '| Tab | Component | Reference RFP |'),
    ('| `zones` | Zone Hint 텍스트 / `ZoneEditor` | LTS-2026-012 |',
     '| `zones` | Zone Hint text / `ZoneEditor` | LTS-2026-012 |'),
    ('> 상세 사양은 각 RFP 문서를 참조한다.', '> See each RFP document for detailed specifications.'),

    # Section 6
    ('## 6. Fullscreen Overlay', '## 6. Fullscreen Overlay'),
    ('### 6.1 개요', '### 6.1 Overview'),
    ('카메라 셀 더블클릭 시 전체 화면 오버레이(`FullscreenCameraView`)가 렌더링된다.',
     'Double-clicking a camera cell renders the full-screen overlay (`FullscreenCameraView`).'),
    ('### 6.2 구조', '### 6.2 Structure'),
    ('│  │    CameraView (flex-1)          │  ┌──── Tab ────────────┐  ││',
     '│  │    CameraView (flex-1)          │  ┌──── Tab ────────────┐  ││'),
    ('│  │                                 │  │  Detection List     │  ││',
     '│  │                                 │  │  Detection List     │  ││'),
    ('│  │                                 │  │  (객체 목록 + 속성) │  ││',
     '│  │                                 │  │  (object list + attrs) │ ││'),
    ('│  │                                 │  │  Video Analytics   │  ││',
     '│  │                                 │  │  Video Analytics   │  ││'),
    ('│  │                                 │  │  Tab (AI 모듈 토글) │  ││',
     '│  │                                 │  │  Tab (AI module toggles) │ ││'),
    ('│                                                         [닫기 X] │',
     '│                                                         [Close X] │'),
    ('### 6.3 동작 요구사항', '### 6.3 Behavior Requirements'),
    ('| 요소 | 사양 |', '| Element | Specification |'),
    ('| **진입** | Camera Grid 셀 더블클릭 |', '| **Entry** | Double-click Camera Grid cell |'),
    ('| **복귀** | 우상단 × 버튼 클릭 또는 `ESC` 키 |', '| **Exit** | Click × button in top-right or press `ESC` key |'),
    ('| **영상** | `CameraView` — WebRTC 또는 JPEG 모드 동일 |',
     '| **Video** | `CameraView` — same WebRTC or JPEG mode |'),
    ('| **감지 오버레이** | Canvas 레이어 — bounding box, 라벨, 속성 배지 |',
     '| **Detection overlay** | Canvas layer — bounding box, labels, attribute badges |'),
    ('| **Detection List** | 좌측 패널 — 감지 객체 목록, 드웰타임, 위험도 |',
     '| **Detection List** | Left panel — detected object list, dwell time, risk score |'),
    ('| **Cross-Camera** | 탭 전환으로 교차 카메라 ReID 이벤트 표시 |',
     '| **Cross-Camera** | Tab switch shows cross-camera ReID events |'),
    ('| **Zone Editor** | 하단 버튼으로 Zone 편집 모드 전환 |',
     '| **Zone Editor** | Bottom button switches to Zone edit mode |'),
    ('| **Video Analytics** | AI 모듈 활성/비활성 토글 패널 (Detection List 아래) |',
     '| **Video Analytics** | AI module enable/disable toggle panel (below Detection List) |'),
    ('### 6.4 Zone Editor 진입', '### 6.4 Zone Editor Entry'),
    ('- FullscreenCameraView 내 `Zone Editor` 버튼 클릭 시 `ZoneEditor` 컴포넌트로 전환',
     '- Clicking the `Zone Editor` button inside FullscreenCameraView switches to the `ZoneEditor` component'),
    ('- 편집 완료 후 다시 `CameraView`로 복귀', '- Returns to `CameraView` after editing is complete'),

    # Section 7
    ('## 7. Settings Modal', '## 7. Settings Modal'),
    ('### 7.1 개요', '### 7.1 Overview'),
    ('Top Bar 설정 아이콘(⚙) 클릭 시 `SettingsModal`이 Modal Overlay로 렌더링된다.',
     'Clicking the Settings icon (⚙) in the Top Bar renders `SettingsModal` as a Modal Overlay.'),
    ('### 7.2 구조', '### 7.2 Structure'),
    ('│  Header: "Settings" + × 버튼     │', '│  Header: "Settings" + × button     │'),
    ('│  │  [언어 선택 섹션]            │ │', '│  │  [Language selection section]  │ │'),
    ('│  │  [WebRTC 섹션]              │ │', '│  │  [WebRTC section]             │ │'),
    ('│  │  • Enable/Disable 토글      │ │', '│  │  • Enable/Disable toggle      │ │'),
    ('│  │  • STUN 서버 목록 (추가/삭제)│ │', '│  │  • STUN server list (add/delete) │ │'),
    ('│  │  • TURN 서버 목록 (추가/삭제)│ │', '│  │  • TURN server list (add/delete) │ │'),
    ('│  │  • Apply 버튼               │ │', '│  │  • Apply button               │ │'),
    ('│  Footer: "닫기" 버튼              │', '│  Footer: "Close" button            │'),
    ('### 7.3 크기 및 동작', '### 7.3 Size and Behavior'),
    ('| 속성 | 값 |', '| Property | Value |'),
    ('| 너비 | `w-96` (384px) |', '| Width | `w-96` (384px) |'),
    ('| 최대 높이 | `max-h-[88vh]` |', '| Max height | `max-h-[88vh]` |'),
    ('| 배경 오버레이 | `bg-black/60` |', '| Background overlay | `bg-black/60` |'),
    ('| 오버레이 클릭 | 모달 닫기 |', '| Overlay click | Close modal |'),
    ('### 7.4 언어 선택 섹션', '### 7.4 Language Selection Section'),
    ('- 지원 언어: 15개 (ko, en, zh-CN, zh-TW, ja, es, fr, de, pt, ru, ar, hi, id, tr, vi)',
     '- Supported languages: 15 (ko, en, zh-CN, zh-TW, ja, es, fr, de, pt, ru, ar, hi, id, tr, vi)'),
    ('- 국기 이모지 + 언어명 목록', '- Flag emoji + language name list'),
    ('- 선택된 언어: 파란 체크 아이콘 + 파란 배경', '- Selected language: blue check icon + blue background'),
    ('### 7.5 WebRTC 설정 섹션', '### 7.5 WebRTC Settings Section'),
    ('| 항목 | 타입 | 설명 |', '| Item | Type | Description |'),
    ('| WebRTC 활성화 | Toggle | mediasoup WebRTC 스트림 사용 여부 |',
     '| WebRTC Enable | Toggle | Whether to use mediasoup WebRTC stream |'),
    ('| STUN 서버 | 문자열 배열 | URL 목록 (추가/삭제) |', '| STUN servers | String array | URL list (add/delete) |'),
    ('| TURN 서버 | 객체 배열 | `{ url, username, credential }` 목록 |',
     '| TURN servers | Object array | `{ url, username, credential }` list |'),
    ('| Apply 버튼 | 버튼 | `localStorage` 저장 + 저장 완료 피드백 |',
     '| Apply button | Button | Save to `localStorage` + save confirmation feedback |'),
    ('- TURN credential 필드: `type="password"`, `autoComplete="new-password"`',
     '- TURN credential field: `type="password"`, `autoComplete="new-password"`'),
    ('- 설정 영속화: Zustand store + `localStorage` key `lts-webrtc-config`',
     '- Settings persistence: Zustand store + `localStorage` key `lts-webrtc-config`'),

    # Section 8
    ('## 8. 반응형 및 레이아웃 제약', '## 8. Responsive & Layout Constraints'),
    ('### 8.1 지원 해상도', '### 8.1 Supported Resolutions'),
    ('| 해상도 | 레이아웃 동작 |', '| Resolution | Layout Behavior |'),
    ('| 1920×1080 이상 | 모든 레이아웃 정상 지원 (64채널 포함) |',
     '| 1920×1080 and above | All layouts fully supported (including 64 channels) |'),
    ('| 1366×768 | 16채널까지 권장; 24/32/64채널 시 셀 소형화 |',
     '| 1366×768 | Recommended up to 16 channels; cells shrink for 24/32/64 channels |'),
    ('| 모바일 | 미지원 (데스크톱 전용) |', '| Mobile | Not supported (desktop only) |'),
    ('### 8.2 오버플로우 처리', '### 8.2 Overflow Handling'),
    ('- 앱 전체: `overflow-hidden` (스크롤 없음)', '- Entire app: `overflow-hidden` (no scroll)'),
    ('- Sidebar: `overflow-hidden` (탭 컨텐츠 내부에서 스크롤)', '- Sidebar: `overflow-hidden` (scroll inside tab content)'),
    ('- Settings Modal 내부: `overflow-y-auto`', '- Settings Modal interior: `overflow-y-auto`'),
    ('### 8.3 z-index 계층', '### 8.3 z-index Layers'),
    ('| 레이어 | z-index | 설명 |', '| Layer | z-index | Description |'),
    ('| 기본 UI | 0 | Grid, Sidebar |', '| Base UI | 0 | Grid, Sidebar |'),
    ('| Discovered Camera Panel | `absolute` | 메인 영역 위 |',
     '| Discovered Camera Panel | `absolute` | Above main area |'),
    ('| Fullscreen Overlay | `z-40` | 전체 앱 위 |', '| Fullscreen Overlay | `z-40` | Above entire app |'),
    ('| Settings Modal | `z-50` | 최상위 |', '| Settings Modal | `z-50` | Topmost |'),

    # Section 9
    ('## 9. 국제화(i18n) 지원', '## 9. Internationalization (i18n) Support'),
    ('### 9.1 지원 언어', '### 9.1 Supported Languages'),
    ('15개 언어 지원. 기본값: 브라우저 언어 감지 → 없으면 `en`.',
     '15 languages supported. Default: browser language detection → falls back to `en`.'),
    ('| 언어 | 코드 | 방향 |', '| Language | Code | Direction |'),
    ('### 9.2 주요 i18n 키 (Dashboard 공통)', '### 9.2 Key i18n Keys (Dashboard common)'),
    ('| 키 | 영문 기본값 | 사용 위치 |', '| Key | English Default | Usage Location |'),
    ('| `connected` | `Connected` | Top Bar 상태 |', '| `connected` | `Connected` | Top Bar status |'),
    ('| `disconnected` | `Disconnected` | Top Bar 상태 |', '| `disconnected` | `Disconnected` | Top Bar status |'),
    ('| `live` | `live` | 카메라 카운트 |', '| `live` | `live` | Camera count |'),
    ('| `tabCameras` | `Cameras` | Sidebar 탭 |', '| `tabCameras` | `Cameras` | Sidebar tab |'),
    ('| `tabAlerts` | `Alerts` | Sidebar 탭 |', '| `tabAlerts` | `Alerts` | Sidebar tab |'),
    ('| `tabZones` | `Zones` | Sidebar 탭 |', '| `tabZones` | `Zones` | Sidebar tab |'),
    ('| `settings` | `Settings` | Top Bar 툴팁 |', '| `settings` | `Settings` | Top Bar tooltip |'),
    ('| `zoneHint` | `Open fullscreen camera view to draw and manage detection zones` | Zones 탭 힌트 |',
     '| `zoneHint` | `Open fullscreen camera view to draw and manage detection zones` | Zones tab hint |'),
    ('| `addCameraFirst` | `Add a camera to get started` | Zones 탭 서브힌트 |',
     '| `addCameraFirst` | `Add a camera to get started` | Zones tab sub-hint |'),
    ('### 9.3 언어 영속화', '### 9.3 Language Persistence'),
    ('- 저장 위치: `localStorage` key `lts-language`', '- Storage: `localStorage` key `lts-language`'),
    ('- 적용: `I18nProvider` 마운트 시 즉시 로드', '- Applied: loaded immediately when `I18nProvider` mounts'),
    ('- RTL (Arabic): `<html dir="rtl">` 동적 적용', '- RTL (Arabic): dynamically applies `<html dir="rtl">`'),

    # Section 10
    ('## 10. 상태 관리 구조', '## 10. State Management Structure'),
    ('### 10.1 Zustand 스토어 목록', '### 10.1 Zustand Store List'),
    ('| 스토어 | 파일 | 주요 상태 |', '| Store | File | Key State |'),
    ('| `useCameraStore` | `stores/cameraStore.ts` | `cameras[]`, `selectedId` |',
     '| `useCameraStore` | `stores/cameraStore.ts` | `cameras[]`, `selectedId` |'),
    ('| `useAlertStore` | `stores/alertStore.ts` | `alerts[]` |',
     '| `useAlertStore` | `stores/alertStore.ts` | `alerts[]` |'),
    ('| `useDiscoveryStore` | `stores/discoveryStore.ts` | `cameras[]`, `selected`, `scanning` |',
     '| `useDiscoveryStore` | `stores/discoveryStore.ts` | `cameras[]`, `selected`, `scanning` |'),
    ('| `useCrossCameraStore` | `stores/crossCameraStore.ts` | `events[]` |',
     '| `useCrossCameraStore` | `stores/crossCameraStore.ts` | `events[]` |'),
    ('| `useWebRTCConfigStore` | `stores/webrtcConfigStore.ts` | `enabled`, `stunUrls[]`, `turns[]` |',
     '| `useWebRTCConfigStore` | `stores/webrtcConfigStore.ts` | `enabled`, `stunUrls[]`, `turns[]` |'),
    ('### 10.2 Socket.IO 이벤트 (Dashboard 레벨)', '### 10.2 Socket.IO Events (Dashboard level)'),
    ('| 이벤트 | 방향 | 처리 위치 |', '| Event | Direction | Handler Location |'),
    ('| `connect` | Server→Client | `connected` 상태 업데이트 |',
     '| `connect` | Server→Client | `connected` state update |'),
    ('| `disconnect` | Server→Client | `connected = false` |',
     '| `disconnect` | Server→Client | `connected = false` |'),
    ('| `cameras` | Server→Client | `setCameras()` |', '| `cameras` | Server→Client | `setCameras()` |'),
    ('| `camera:status` | Server→Client | `updateCameraStatus()` |',
     '| `camera:status` | Server→Client | `updateCameraStatus()` |'),
    ('| `alert` | Server→Client | `addAlert()` |', '| `alert` | Server→Client | `addAlert()` |'),
    ('| `cross-camera:reid` | Server→Client | `addCrossCameraEvent()` |',
     '| `cross-camera:reid` | Server→Client | `addCrossCameraEvent()` |'),
    ('| `discovery:result` | Server→Client | CameraList에서 처리 |',
     '| `discovery:result` | Server→Client | Handled in CameraList |'),
    ('| `discovery:scanning` | Server→Client | CameraList에서 처리 |',
     '| `discovery:scanning` | Server→Client | Handled in CameraList |'),

    # Section 11
    ('## 11. 구현 현황', '## 11. Implementation Status'),
    ('### 11.1 Phase-1 완료 항목', '### 11.1 Phase-1 Completed Items'),
    ('| 항목 | 상태 | 비고 |', '| Item | Status | Notes |'),
    ('| 전체 레이아웃 구조 (Header/Grid/Sidebar) | ✅ 완료 | `App.tsx` |',
     '| Full layout structure (Header/Grid/Sidebar) | ✅ Done | `App.tsx` |'),
    ('| Top Bar (로고, 연결상태, 카운트, 레이아웃 피커, 설정) | ✅ 완료 | |',
     '| Top Bar (logo, connection status, count, layout picker, settings) | ✅ Done | |'),
    ('| Camera Grid — Equal Grid (1/2/4/5/8/9/12/16/24/32/64) | ✅ 완료 | `CameraGrid.tsx` |',
     '| Camera Grid — Equal Grid (1/2/4/5/8/9/12/16/24/32/64) | ✅ Done | `CameraGrid.tsx` |'),
    ('| Camera Grid — Featured Layout (1+3/1+4/1+7/1+11/1+15) | ✅ 완료 | `CameraGrid.tsx` |',
     '| Camera Grid — Featured Layout (1+3/1+4/1+7/1+11/1+15) | ✅ Done | `CameraGrid.tsx` |'),
    ('| LayoutPicker 드롭다운 (SVG 아이콘 + 16종 그룹 선택) | ✅ 완료 | `App.tsx` |',
     '| LayoutPicker dropdown (SVG icons + 16 layout group selection) | ✅ Done | `App.tsx` |'),
    ('| Compact 모드 (16채널 이상 — 오버레이 최소화) | ✅ 완료 | `CameraGrid.tsx` |',
     '| Compact mode (16+ channels — minimize overlays) | ✅ Done | `CameraGrid.tsx` |'),
    ('| Camera Grid 더블클릭 Fullscreen 진입 | ✅ 완료 | |',
     '| Camera Grid double-click Fullscreen entry | ✅ Done | |'),
    ('| Sidebar 탭 구조 (Cameras/Alerts/Zones) | ✅ 완료 | |',
     '| Sidebar tab structure (Cameras/Alerts/Zones) | ✅ Done | |'),
    ('| Alerts 탭 배지 (미확인 수) | ✅ 완료 | |', '| Alerts tab badge (unacknowledged count) | ✅ Done | |'),
    ('| Fullscreen Overlay | ✅ 완료 | `FullscreenCameraView.tsx` |',
     '| Fullscreen Overlay | ✅ Done | `FullscreenCameraView.tsx` |'),
    ('| Settings Modal (언어, WebRTC) | ✅ 완료 | |', '| Settings Modal (language, WebRTC) | ✅ Done | |'),
    ('| 다국어 지원 15개 언어 | ✅ 완료 | |', '| 15-language multilingual support | ✅ Done | |'),
    ('| WebRTC 설정 영속화 (localStorage) | ✅ 완료 | |', '| WebRTC settings persistence (localStorage) | ✅ Done | |'),
    ('| 다크 테마 | ✅ 완료 | Tailwind CSS gray-800/900 |', '| Dark theme | ✅ Done | Tailwind CSS gray-800/900 |'),
    ('### 11.2 미구현 / 개선 예정 항목', '### 11.2 Not Yet Implemented / Planned Improvements'),
    ('| 항목 | 우선순위 | 비고 |', '| Item | Priority | Notes |'),
    ('| 모바일/태블릿 반응형 레이아웃 | 중 | 현재 데스크톱 전용 |',
     '| Mobile/tablet responsive layout | Medium | Currently desktop only |'),
    ('| 레이아웃 영속화 (localStorage 저장) | 중 | 새로고침 후 마지막 레이아웃 복원 |',
     '| Layout persistence (localStorage) | Medium | Restore last layout after refresh |'),
    ('| 카메라 드래그&드롭 재배열 | 하 | |', '| Camera drag & drop reorder | Low | |'),
    ('| 대시보드 위젯 토글 (통계 패널 등) | 하 | |', '| Dashboard widget toggle (stats panel etc.) | Low | |'),
    ('| 경보 음향 알림 | 중 | AlertPanel 연동 필요 |', '| Alert audio notification | Medium | AlertPanel integration required |'),
    ('| 전체화면 API (`requestFullscreen`) | 하 | 현재 CSS 전체화면 방식 |',
     '| Fullscreen API (`requestFullscreen`) | Low | Currently CSS fullscreen approach |'),
]

result = translate_file(f'{BASE}/RFP_Dashboard_Layout.md', layout_replacements)
print(f"RFP_Dashboard_Layout.md: {'updated' if result else 'no changes'}")

print("Phase 2 part 1 complete.")
