import re
import os

def translate_file(filepath, replacements):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original = content
    for korean, english in replacements:
        content = content.replace(korean, english)
    
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False

BASE = '/home/youngho/workspace/loitering_tracking'

# ============================================================
# README.md
# ============================================================
readme_replacements = [
    # Table of Contents ICE candidate
    ('1. [Project Overview](#1-project-overview) — [Quick Commands](#14-quick-commands) · [ICE Candidate 테스트](#15-ice-candidate-테스트)',
     '1. [Project Overview](#1-project-overview) — [Quick Commands](#14-quick-commands) · [ICE Candidate Test](#15-ice-candidate-test)'),
    
    # Section 1.4 Quick Commands
    ('#### 서버 시작 / 정지', '#### Server Start / Stop'),
    ('# 개발 모드 (파일 변경 시 자동 재시작)', '# Development mode (auto-restart on file changes)'),
    ('# 운영 모드\ncd server && npm start', '# Production mode\ncd server && npm start'),
    ('# 정지: Ctrl+C\n```\n\n#### Web UI 시작 / 정지', '# Stop: Ctrl+C\n```\n\n#### Web UI Start / Stop'),
    ('# 개발 모드 (Vite dev server — http://localhost:5173)', '# Development mode (Vite dev server — http://localhost:5173)'),
    ('# 운영용 빌드 (dist/ 폴더 생성)', '# Production build (creates dist/ folder)'),
    ('# 정지: Ctrl+C\n```\n\n#### 서버 상태 확인 (Health Check)', '# Stop: Ctrl+C\n```\n\n#### Server Status Check (Health Check)'),
    ('카메라 파이프라인, WebRTC ICE 설정, AI 모듈, mediasoup UDP 포트를 한 번에 점검합니다.',
     'Checks the camera pipeline, WebRTC ICE settings, AI modules, and mediasoup UDP ports in one step.'),
    ('# 로컬 서버 확인 (기본: http://localhost:3001)', '# Local server check (default: http://localhost:3001)'),
    ('# 원격 서버 지정\nnode server/src/scripts/healthCheck.js', '# Specify remote server\nnode server/src/scripts/healthCheck.js'),
    ('출력 예시:', 'Output example:'),

    # Section 1.4 ICE/STUN
    ('#### ICE / STUN / TURN 설정 확인\n\n서버가 브라우저에 내려주는 ICE 서버 목록을 조회합니다.',
     '#### ICE / STUN / TURN Configuration Check\n\nRetrieves the ICE server list sent by the server to the browser.'),
    ('# ICE 설정 JSON 조회 (server/.env의 STUN/TURN 값 반영)', '# Retrieve ICE config JSON (reflects STUN/TURN values from server/.env)'),
    ('#### TURN 서버 UDP 연결 테스트', '#### TURN Server UDP Connection Test'),
    ('# coturn 서비스 상태 확인', '# Check coturn service status'),
    ('# TURN 포트(3478) UDP 응답 확인 — 로컬', '# Verify TURN port (3478) UDP response — local'),
    ('# mediasoup WebRTC 포트 범위 확인 (브라우저 연결 후 생성됨)', '# Verify mediasoup WebRTC port range (created after browser connects)'),

    # Section 1.5
    ('### 1.5 ICE Candidate 테스트\n\nWebRTC 연결이 어떤 경로(LAN 직접 / STUN / TURN)를 사용하는지 확인하는 방법 3가지입니다.',
     '### 1.5 ICE Candidate Test\n\nThree methods to verify which path (direct LAN / STUN / TURN) the WebRTC connection is using.'),
    ('#### 방법 1 — Web UI ICE 패널 (권장)', '#### Method 1 — Web UI ICE Panel (recommended)'),
    ('카메라가 WebRTC로 연결된 상태에서 우상단 **ICE** 버튼을 클릭합니다.',
     'While the camera is connected via WebRTC, click the **ICE** button in the top-right corner.'),
    ('**ICE 버튼 색상 의미 (local candidate type):**', '**ICE Button Color Meaning (local candidate type):**'),
    ('| 표시 | 타입 | 의미 | 상태 |', '| Indicator | Type | Meaning | Status |'),
    ('| `[host]` | host | LAN 직접 연결 (최적) | 🟢 |', '| `[host]` | host | Direct LAN connection (optimal) | 🟢 |'),
    ('| `[srflx]` | srflx | STUN으로 공인 IP 취득, NAT 통과 | 🟡 |', '| `[srflx]` | srflx | Public IP obtained via STUN, NAT traversal | 🟡 |'),
    ('| `[relay]` | relay | TURN 릴레이 경유 (방화벽/인터넷 환경) | 🟠 |', '| `[relay]` | relay | Via TURN relay (firewall/internet environment) | 🟠 |'),
    ('> **패널 갱신 주기**: 3초마다 `RTCPeerConnection.getStats()` 호출 — 바이트 카운터로 실제 데이터 흐름 확인 가능',
     '> **Panel refresh interval**: `RTCPeerConnection.getStats()` called every 3 seconds — byte counter allows verification of actual data flow'),
    ('#### 방법 2 — 브라우저 내장 WebRTC 진단\n\n연결 중 아무 때나 새 탭에서 열면 전체 ICE 협상 과정과 stats를 볼 수 있습니다.',
     '#### Method 2 — Browser built-in WebRTC Diagnostics\n\nOpen in a new tab at any time during connection to view the full ICE negotiation process and stats.'),
    ('확인 포인트:', 'Check points:'),
    ('- **ICE candidate grid** — 수집된 모든 후보 목록 (host / srflx / relay)',
     '- **ICE candidate grid** — List of all collected candidates (host / srflx / relay)'),
    ('- **candidatepairchanged** — 선택된 pair 변경 이력',
     '- **candidatepairchanged** — Selected pair change history'),
    ('- **Selected Candidate Pair** — 현재 사용 중인 local↔remote 경로',
     '- **Selected Candidate Pair** — Currently active local↔remote path'),
    ('- **inbound-rtp** — 수신 패킷 수 / 손실률 (jitter, packetsLost)',
     '- **inbound-rtp** — Received packet count / loss rate (jitter, packetsLost)'),
    ('- **connection-state** → `connected` 유지 여부',
     '- **connection-state** → Whether `connected` is maintained'),
    ('#### 방법 3 — 서버 명령줄\n\n서버에서 ICE 관련 설정과 포트를 직접 확인합니다.',
     '#### Method 3 — Server command line\n\nDirectly verify ICE-related settings and ports from the server.'),
    ('# ① 서버가 브라우저에 내려주는 STUN/TURN 목록 조회', '# ① Retrieve STUN/TURN list sent by the server to the browser'),
    ('# ② STUN Binding Request로 coturn UDP 3478 포트 응답 확인', '# ② Verify coturn UDP 3478 port response via STUN Binding Request'),
    ('# ③ mediasoup가 열어둔 WebRTC UDP 포트 확인 (브라우저 연결 후 생성됨)', '# ③ Check mediasoup WebRTC UDP ports (created after browser connects)'),
    ('# ④ 전체 헬스체크 (cameras + ICE config + AI + mediasoup ports)', '# ④ Full health check (cameras + ICE config + AI + mediasoup ports)'),
    ('#### ICE 연결 문제 진단 흐름', '#### ICE Connection Problem Diagnosis Flow'),
    ('연결 실패 / 영상 정지', 'Connection failed / Video frozen'),
    ('       ├─ local: relay → TURN 경로 사용 중', '       ├─ local: relay → TURN relay path in use'),
    ('       │    └─ coturn 설정 확인: systemctl status coturn', '       │    └─ Check coturn config: systemctl status coturn'),
    ('       │       allowed-peer-ip=192.168.214.3 추가 필요 여부 확인', '       │       Check if allowed-peer-ip=192.168.214.3 addition needed'),
    ('       ├─ local: srflx → STUN 공인 IP 경유', '       ├─ local: srflx → Via STUN public IP'),
    ('       │    └─ 헤어핀 NAT 문제일 수 있음', '       │    └─ Hairpin NAT may be the problem'),
    ('       │       server/.env: SERVER_IP=<LAN IP> 로 설정 확인', '       │       Check server/.env: SERVER_IP=<LAN IP> setting'),
    ('       ├─ local: host → LAN 직접, 그런데 실패', '       ├─ local: host → Direct LAN, but failed'),
    ('       │    └─ mediasoup UDP 포트 방화벽 확인', '       │    └─ Check mediasoup UDP port firewall'),
    ('       └─ 패널이 안 뜸 (ICE 버튼 없음)', '       └─ Panel does not appear (no ICE button)'),
    ('            └─ WebRTC 연결 자체 실패 → npm run health 로 서버 상태 확인', '            └─ WebRTC connection itself failed → check server status with npm run health'),

    # Section 7.1 table
    ('| 1 | ☑ **Human** | `human` | [AI-01](RFP_AI_Human_Detection.md) | ✅ 구현 완료 | 사람 감지 — YOLOv8n COCO class 0 (person) |',
     '| 1 | ☑ **Human** | `human` | [AI-01](RFP_AI_Human_Detection.md) | ✅ Implemented | Person detection — YOLOv8n COCO class 0 (person) |'),
    ('| 2 | ☑ **Vehicle** | `vehicle` | [AI-02](RFP_AI_Vehicle_Detection.md) | ✅ 구현 완료 | 차량 감지 — bicycle/car/motorcycle/bus/truck |',
     '| 2 | ☑ **Vehicle** | `vehicle` | [AI-02](RFP_AI_Vehicle_Detection.md) | ✅ Implemented | Vehicle detection — bicycle/car/motorcycle/bus/truck |'),
    ('| 3 | ☑ **Face** | `face` | [AI-03](RFP_AI_Face_Recognition.md) | ✅ 구현 완료 | 얼굴 감지 — SCRFD-2.5G (3.2MB) + ArcFace ResNet50 Re-ID (249MB) |',
     '| 3 | ☑ **Face** | `face` | [AI-03](RFP_AI_Face_Recognition.md) | ✅ Implemented | Face detection — SCRFD-2.5G (3.2MB) + ArcFace ResNet50 Re-ID (249MB) |'),
    ('| 4 | ☑ **Mask** | `mask` | [AI-04](RFP_AI_Mask_Detection.md) | ✅ 구현 완료 | 마스크 착용 감지 — YOLOv8m PPE (99MB), mask/no_mask 2-class |',
     '| 4 | ☑ **Mask** | `mask` | [AI-04](RFP_AI_Mask_Detection.md) | ✅ Implemented | Mask detection — YOLOv8m PPE (99MB), mask/no_mask 2-class |'),
    ('| 5 | ☑ **Color** | `color` | [AI-05](RFP_AI_Color_Analysis.md) | ✅ 구현 완료 | 상/하의 색상 분석 — Phase-1 픽셀 평균, 11색 분류 (모델 불필요) |',
     '| 5 | ☑ **Color** | `color` | [AI-05](RFP_AI_Color_Analysis.md) | ✅ Implemented | Upper/lower body color analysis — Phase-1 pixel average, 11-color classification (no model required) |'),
    ('| 6 | ☐ **Cloth** | `cloth` | [AI-06](RFP_AI_Cloth_Analysis.md) | 🔲 준비중 | 의류 유형 분류 — OpenPAR (openpar.onnx 미설치) |',
     '| 6 | ☐ **Cloth** | `cloth` | [AI-06](RFP_AI_Cloth_Analysis.md) | 🔲 Pending | Clothing type classification — OpenPAR (openpar.onnx not installed) |'),
    ('| 7 | ☑ **Hat** | `hat` | [AI-07](RFP_AI_Hat_Detection.md) | ✅ 구현 완료 | 헬멧/모자 감지 — YOLOv8m PPE (99MB), hardhat/no_hardhat 분류 |',
     '| 7 | ☑ **Hat** | `hat` | [AI-07](RFP_AI_Hat_Detection.md) | ✅ Implemented | Helmet/hat detection — YOLOv8m PPE (99MB), hardhat/no_hardhat classification |'),
    ('| 8 | ☑ **Accessories** | `accessories` | [AI-08](RFP_AI_Accessories_Detection.md) | ✅ 구현 완료 | 소품 감지 — YOLOv8n COCO (backpack/umbrella/handbag/tie/suitcase) |',
     '| 8 | ☑ **Accessories** | `accessories` | [AI-08](RFP_AI_Accessories_Detection.md) | ✅ Implemented | Accessories detection — YOLOv8n COCO (backpack/umbrella/handbag/tie/suitcase) |'),
    ('| 9 | ☑ **Fire** | `fire` | [AI-09](RFP_AI_Fire_Smoke_Detection.md) | ✅ 구현 완료 | 화재 감지 — YOLOv8s 3-class (yolov8s_fire_smoke.onnx 43MB, Abonia1/GitHub) |',
     '| 9 | ☑ **Fire** | `fire` | [AI-09](RFP_AI_Fire_Smoke_Detection.md) | ✅ Implemented | Fire detection — YOLOv8s 3-class (yolov8s_fire_smoke.onnx 43MB, Abonia1/GitHub) |'),
    ('| 10 | ☑ **Smoke** | `smoke` | [AI-09](RFP_AI_Fire_Smoke_Detection.md) | ✅ 구현 완료 | 연기 감지 — YOLOv8s 3-class (yolov8s_fire_smoke.onnx 43MB, Abonia1/GitHub) |',
     '| 10 | ☑ **Smoke** | `smoke` | [AI-09](RFP_AI_Fire_Smoke_Detection.md) | ✅ Implemented | Smoke detection — YOLOv8s 3-class (yolov8s_fire_smoke.onnx 43MB, Abonia1/GitHub) |'),

    ('> **구현 완료** 모듈은 Zone 편집 시 체크박스가 활성화됩니다. **준비중** 모듈은 체크박스가 회색으로 표시되며 해당 ONNX 모델 파일이 `server/models/`에 배치되면 자동 활성화됩니다.\n>\n> 체크박스 가용성은 서버 `/api/capabilities` 엔드포인트에서 실시간으로 조회됩니다.',
     '> **Implemented** modules: checkbox is enabled when editing a Zone. **Pending** modules: checkbox is shown in gray and automatically activated when the corresponding ONNX model file is placed in `server/models/`.\n>\n> Checkbox availability is queried in real-time from the server `/api/capabilities` endpoint.'),

    ('### 7.2 Zone Editor UI — AI 감지 대상 체크박스\n\nZone 편집 화면 하단의 **"AI 감지 대상"** 섹션에서 해당 Zone에 적용할 AI 모듈을 선택합니다.',
     '### 7.2 Zone Editor UI — AI Detection Target Checkboxes\n\nAt the bottom of the edit screen in the **"AI Detection Targets"** section, select the AI modules to apply to this zone.'),

    ('│ AI 감지 대상  (미선택 시 전체)   │', '│ AI Detection Targets  (All if none selected)   │'),
    ('│ ☑ 사람         │ ☑ 차량         │', '│ ☑ Human        │ ☑ Vehicle      │'),
    ('│ ☑ 얼굴         │ ☑ 마스크        │', '│ ☑ Face         │ ☑ Mask         │'),
    ('│ ☑ 색상         │ ☐ 의류   준비중 │', '│ ☑ Color        │ ☐ Cloth Pending│'),
    ('│ ☑ 모자         │ ☑ 소품          │', '│ ☑ Hat          │ ☑ Accessories  │'),
    ('│ ☑ 화재          │ ☑ 연기          │', '│ ☑ Fire         │ ☑ Smoke        │'),

    ('- **체크 선택**: 파란색 배경 + 체크 아이콘, 즉시 API 저장 (PUT `/api/cameras/:id/zones/:zoneId`)',
     '- **Checkbox selected**: Blue background + check icon, immediately saved via API (PUT `/api/cameras/:id/zones/:zoneId`)'),
    ('- **미선택 시**: `targetClasses: []` → 모든 활성 클래스 감지 (기본 동작)',
     '- **If not selected**: `targetClasses: []` → detect all active classes (default behavior)'),
    ('- **준비중 항목**: 비활성(회색), "준비중" 뱃지 표시, 클릭 불가',
     '- **Pending items**: disabled (gray), "Pending" badge displayed, not clickable'),
    ('- **가용성 동적 조회**: Zone Editor 열릴 때 `/api/capabilities` 호출 → 모델 파일 존재 여부 반영',
     '- **Dynamic availability query**: `/api/capabilities` called when Zone Editor opens → reflects model file existence'),
    ('- **화재/연기 경보**: Zone에 fire/smoke 체크 후 탐지 시 `fire:alert` Socket 이벤트 발생 (10초 쿨다운)',
     '- **Fire/smoke alert**: upon detection after checking fire/smoke in a Zone, `fire:alert` Socket event triggered (10-second cooldown)'),

    ('### 7.3 `targetClasses` 동작 규칙', '### 7.3 `targetClasses` Behavior Rules'),
    ('  // 향후 추가: face, mask, color, cloth, hat, accessories', '  // future additions: face, mask, color, cloth, hat, accessories'),
    ('// targetClasses가 비어있으면 모든 클래스 허용', '// empty means all classes allowed'),

    ('| `targetClasses` 설정 | 감지 대상 | 사용 사례 |', '| `targetClasses` Setting | Detection Targets | Use Case |'),
    ('| `[]` (기본) | 모든 활성 클래스 | 일반 감시 |', '| `[]` (default) | All active classes | General surveillance |'),
    ('| `["human"]` | 사람만 | 출입 통제 구역 |', '| `["human"]` | Persons only | Access-controlled area |'),
    ('| `["vehicle"]` | 차량만 | 주차장 관리 |', '| `["vehicle"]` | Vehicles only | Parking lot management |'),
    ('| `["human", "vehicle"]` | 사람 + 차량 | 혼합 구역 |', '| `["human", "vehicle"]` | Persons + Vehicles | Mixed area |'),
    ('| `["human", "hat"]` | 사람 + 안전모 검사 | 건설 현장 컴플라이언스 *(준비중)* |',
     '| `["human", "hat"]` | Persons + Safety helmet check | Construction site compliance *(Pending)* |'),
    ('| `["human", "mask"]` | 사람 + 마스크 | 방역 구역 *(준비중)* |',
     '| `["human", "mask"]` | Persons + Mask | Quarantine zone *(Pending)* |'),

    ('### 7.4 Bounding Box 색상 코드 (화면 표시)', '### 7.4 Bounding Box Color Codes (Screen Display)'),
    ('| 클래스 | 정상 색상 | Loitering 색상 |', '| Class | Normal color | Loitering color |'),
    ('| person | 🟢 녹색 `rgba(34,197,94)` | 🔴 빨간색 `rgba(239,68,68)` |',
     '| person | 🟢 Green `rgba(34,197,94)` | 🔴 Red `rgba(239,68,68)` |'),
    ('| bicycle | 🟡 노란색 `rgba(250,204,21)` | 🔴 빨간색 |',
     '| bicycle | 🟡 Yellow `rgba(250,204,21)` | 🔴 Red |'),
    ('| car | 🔵 파란색 `rgba(59,130,246)` | 🔴 빨간색 |',
     '| car | 🔵 Blue `rgba(59,130,246)` | 🔴 Red |'),
    ('| motorcycle | 🟠 주황색 `rgba(249,115,22)` | 🔴 빨간색 |',
     '| motorcycle | 🟠 Orange `rgba(249,115,22)` | 🔴 Red |'),
    ('| bus | 🟣 보라색 `rgba(168,85,247)` | 🔴 빨간색 |',
     '| bus | 🟣 Purple `rgba(168,85,247)` | 🔴 Red |'),
    ('| truck | 🩵 청록색 `rgba(20,184,166)` | 🔴 빨간색 |',
     '| truck | 🩵 Teal `rgba(20,184,166)` | 🔴 Red |'),
    ('라벨 형식: `person #3  94%` (className + objectId + confidence)',
     'Label format: `person #3  94%` (className + objectId + confidence)'),

    ('### 7.5 설치된 AI 모델 파일 현황', '### 7.5 Installed AI Model File Status'),
    ('> 검증 환경: **onnxruntime-node 1.26.0** (Node.js, 2026-05-18)  \n> Python onnxruntime 1.14.1은 `yolov8n.onnx` (ONNX IR v9) 미지원 — Node.js 런타임에서만 동작',
     '> Verification environment: **onnxruntime-node 1.26.0** (Node.js, 2026-05-18)  \n> Python onnxruntime 1.14.1 does not support `yolov8n.onnx` (ONNX IR v9) — works only with Node.js runtime'),
    ('| 파일 | 크기 | Node.js 로드 | 담당 AI 모듈 | 출처 |', '| File | Size | Node.js Load | Responsible AI module | Source |'),
    ('| `yolov8n.onnx` | 13 MB | ✅ 동작 | AI-01 Human · AI-02 Vehicle · AI-08 Accessories · Indoor 객체 전체 | Ultralytics YOLOv8n COCO (ONNX IR v9) |',
     '| `yolov8n.onnx` | 13 MB | ✅ Working | AI-01 Human · AI-02 Vehicle · AI-08 Accessories · All indoor objects | Ultralytics YOLOv8n COCO (ONNX IR v9) |'),
    ('| `scrfd_2.5g.onnx` | 3.2 MB | ✅ 동작 | AI-03 Face Detection (얼굴 감지) | JackCui/facefusion @ HuggingFace |',
     '| `scrfd_2.5g.onnx` | 3.2 MB | ✅ Working | AI-03 Face Detection | JackCui/facefusion @ HuggingFace |'),
    ('| `arcface_w600k_r50.onnx` | 249 MB | ✅ 동작 | AI-03 Face Re-ID (얼굴 재식별) | FoivosPar/Arc2Face @ HuggingFace |',
     '| `arcface_w600k_r50.onnx` | 249 MB | ✅ Working | AI-03 Face Re-ID | FoivosPar/Arc2Face @ HuggingFace |'),
    ('| `yolov8m_ppe.onnx` | 99 MB | ✅ 동작 | AI-04 Mask Detection · AI-07 Helmet Detection | keremberke/yolov8m-protective-equipment-detection |',
     '| `yolov8m_ppe.onnx` | 99 MB | ✅ Working | AI-04 Mask Detection · AI-07 Helmet Detection | keremberke/yolov8m-protective-equipment-detection |'),
    ('| `yolov8s_fire_smoke.onnx` | 43 MB | ✅ 동작 | AI-09 Fire & Smoke Detection (화재·연기 3-class) | Abonia1/YOLOv8-Fire-and-Smoke-Detection @ GitHub |',
     '| `yolov8s_fire_smoke.onnx` | 43 MB | ✅ Working | AI-09 Fire & Smoke Detection (3-class) | Abonia1/YOLOv8-Fire-and-Smoke-Detection @ GitHub |'),
    ('| `openpar.onnx` | — | 🔲 미설치 | AI-06 Cloth Analysis Phase-2 (의류 유형 분류) | Event-AHU/OpenPAR (연구 프레임워크 — 별도 학습 필요) |',
     '| `openpar.onnx` | — | 🔲 Not installed | AI-06 Cloth Analysis Phase-2 (Clothing type classification) | Event-AHU/OpenPAR (research framework — separate training required) |'),
    ('**모델 합계**: 설치 완료 5개 · 총 약 407 MB  \n**미설치**: 1개 (`openpar.onnx`) — Phase-2 구현 대기 (추론 코드 미완성)',
     '**Total models**: 5 installed · Total approximately 407 MB  \n**Not installed**: 1 (`openpar.onnx`) — Pending Phase-2 implementation (inference code incomplete)'),
    ('├── scrfd_2.5g.onnx                 3.2 MB  ✅     얼굴 감지 SCRFD-2.5G (AI-03)',
     '├── scrfd_2.5g.onnx                 3.2 MB  ✅     Face detection SCRFD-2.5G (AI-03)'),
    ('├── arcface_w600k_r50.onnx          249 MB  ✅     얼굴 Re-ID ArcFace ResNet50 (AI-03)',
     '├── arcface_w600k_r50.onnx          249 MB  ✅     Face Re-ID ArcFace ResNet50 (AI-03)'),
    ('├── yolov8m_ppe.onnx                 99 MB  ✅     마스크/헬멧 YOLOv8m PPE (AI-04/07)',
     '├── yolov8m_ppe.onnx                 99 MB  ✅     Mask/Helmet YOLOv8m PPE (AI-04/07)'),
    ('└── yolov8s_fire_smoke.onnx          43 MB  ✅     화재/연기 YOLOv8s 3-class (AI-09)',
     '└── yolov8s_fire_smoke.onnx          43 MB  ✅     Fire/Smoke YOLOv8s 3-class (AI-09)'),
    ('                                              출처: Abonia1/YOLOv8-Fire-and-Smoke-Detection',
     '                                              Source: Abonia1/YOLOv8-Fire-and-Smoke-Detection'),
    ('[미설치]\n└── openpar.onnx                      — MB  🔲     의류 유형 PAR (AI-06 Phase-2)',
     '[Not installed]\n└── openpar.onnx                      — MB  🔲     Clothing type PAR (AI-06 Phase-2)'),
    ('                                              출처: Event-AHU/OpenPAR (학습 완료 후 ONNX 변환 필요)',
     '                                              Source: Event-AHU/OpenPAR (ONNX conversion required after training)'),
    ('                                              ※ colorClothService._runPAR() 추론 구현 병행 필요',
     '                                              ※ Parallel inference implementation required for colorClothService._runPAR()'),
    ('> **AI-06 Cloth Phase-2 설치 조건** (현재 미완):  \n> 1. Event-AHU/OpenPAR 사전 학습 가중치 다운로드 및 ONNX 변환  \n> 2. `server/src/services/colorClothService.js` → `_runPAR()` 추론 코드 구현  \n> 3. 완료 후 `/api/capabilities` → `cloth: true` 자동 전환  \n> Phase-1 (상체·하체 색상 추출)은 모델 없이 즉시 동작 중.',
     '> **AI-06 Cloth Phase-2 installation requirements** (currently incomplete):  \n> 1. Download pretrained weights from Event-AHU/OpenPAR and convert to ONNX  \n> 2. Implement `_runPAR()` inference code in `server/src/services/colorClothService.js`  \n> 3. After completion, `/api/capabilities` → `cloth: true` automatic switch  \n> Phase-1 (upper/lower body color extraction) is already working immediately without a model.'),
    ('각 AI 모듈 상세 사양: `RFP_AI_Human_Detection.md` ~ `RFP_AI_Fire_Smoke_Detection.md` 참고.',
     'For detailed spec for each AI module, refer to `RFP_AI_Human_Detection.md` through `RFP_AI_Fire_Smoke_Detection.md`.'),

    # Zone Editor vertex delete
    ('| Vertex delete | Right-click on vertex → context menu shows "꼭짓점 N 삭제"; auto-saves after deletion; minimum 3 vertices enforced |',
     '| Vertex delete | Right-click on vertex → context menu shows "Delete vertex N"; auto-saves after deletion; minimum 3 vertices enforced |'),
]

result = translate_file(f'{BASE}/README.md', readme_replacements)
print(f"README.md: {'updated' if result else 'no changes'}")

# ============================================================
# RFP_AI_Fire_Smoke_Detection.md
# ============================================================
fire_smoke_replacements = [
    ('# RFP AI-09: Fire & Smoke Detection (화재/연기 감지)', '# RFP AI-09: Fire & Smoke Detection'),
    ('**문서 ID**: LTS-2026-AI-09  \n**버전**: 1.1  \n**작성일**: 2026-05-15  \n**수정일**: 2026-05-18  \n**상태**: ✅ 구현 완료 (yolov8s_fire_smoke.onnx 설치됨)',
     '**Document ID**: LTS-2026-AI-09  \n**Version**: 1.1  \n**Date**: 2026-05-15  \n**Revised**: 2026-05-18  \n**Status**: ✅ Implemented (yolov8s_fire_smoke.onnx installed)'),
    ('## 1. 개요 (Overview)', '## 1. Overview'),
    ('### 1.1 목적', '### 1.1 Purpose'),
    ('CCTV 영상에서 실시간으로 화재(Fire) 및 연기(Smoke)를 감지하여 조기 경보를 발령하는 AI 모듈. 기존 로이터링 감지 시스템(LTS)에 안전 이벤트 탐지 기능을 추가한다.',
     'An AI module that detects fire and smoke in real time from CCTV video and issues early alerts. Adds safety event detection to the existing Loitering Detection System (LTS).'),
    ('### 1.2 적용 시나리오', '### 1.2 Application Scenarios'),
    ('| 구분 | 시나리오 | 우선순위 |', '| Category | Scenario | Priority |'),
    ('| 건물 내부 | 서버실, 창고, 공장 라인 화재 조기 감지 | ★★★ |', '| Indoor | Early fire detection in server rooms, warehouses, factory lines | ★★★ |'),
    ('| 야외 | 주차장, 야적장, 물류센터 화재 감지 | ★★★ |', '| Outdoor | Fire detection in parking lots, open storage, logistics centers | ★★★ |'),
    ('| 산림 인접 | 산불 초기 연기 감지 | ★★ |', '| Forest Adjacent | Early smoke detection for wildfires | ★★ |'),
    ('| 주방/조리시설 | 조리 연기와 화재 연기 구분 | ★★ |', '| Kitchen/Cooking Facility | Distinguish cooking smoke from fire smoke | ★★ |'),
    ('### 1.3 기대 효과', '### 1.3 Expected Benefits'),
    ('- 화재 발생 후 **30초 이내** 조기 탐지 (기존 스프링클러 비교 5분 이상 단축)',
     '- Early detection within **30 seconds** of fire occurrence (reduces time by 5+ minutes compared to sprinkler systems)'),
    ('- 야간/저조도 환경에서도 화염 빛 특성 기반 감지',
     '- Detection based on flame light characteristics even in night/low-light environments'),
    ('- 기존 CCTV 인프라 재활용 (추가 센서 불필요)',
     '- Reuses existing CCTV infrastructure (no additional sensors required)'),
    ('## 2. 기술 요구사항', '## 2. Technical Requirements'),
    ('### 2.1 기능 요구사항', '### 2.1 Functional Requirements'),
    ('| ID | 요구사항 | 수준 |', '| ID | Requirement | Level |'),
    ('| FS-01 | YOLOv8 기반 실시간 화재(fire) / 연기(smoke) bbox 탐지 | 필수 |',
     '| FS-01 | YOLOv8-based real-time fire / smoke bbox detection | Required |'),
    ('| FS-02 | Zone 설정으로 감시 영역 제한 | 필수 |', '| FS-02 | Restrict monitoring area via Zone configuration | Required |'),
    ('| FS-03 | 감지 즉시 `fire:alert` Socket.IO 이벤트 발생 | 필수 |', '| FS-03 | Immediately emit `fire:alert` Socket.IO event upon detection | Required |'),
    ('| FS-04 | 감지 신뢰도(confidence) 임계값 설정 가능 | 필수 |', '| FS-04 | Configurable detection confidence threshold | Required |'),
    ('| FS-05 | 화재/연기 bbox를 카메라 뷰 오버레이에 표시 | 필수 |', '| FS-05 | Display fire/smoke bbox on camera view overlay | Required |'),
    ('| FS-06 | 좌측 Detection 패널에 fire/smoke 탐지 항목 표시 | 필수 |', '| FS-06 | Display fire/smoke detection items in left Detection panel | Required |'),
    ('| FS-07 | 야간/저조도 조건에서도 동작 | 권장 |', '| FS-07 | Operate in night/low-light conditions | Recommended |'),
    ('| FS-08 | 연기(smoke)와 수증기(steam) 구분 | 권장 |', '| FS-08 | Distinguish smoke from steam | Recommended |'),
    ('### 2.2 성능 요구사항', '### 2.2 Performance Requirements'),
    ('| 지표 | 목표값 | 비고 |', '| Metric | Target | Notes |'),
    ('| mAP@0.5 | ≥ 0.80 | D-Fire 기준 |', '| mAP@0.5 | ≥ 0.80 | D-Fire benchmark |'),
    ('| 처리 속도 | ≥ 10 FPS (CPU) | 640×640 입력 |', '| Processing speed | ≥ 10 FPS (CPU) | 640×640 input |'),
    ('| 탐지 지연 | ≤ 200ms | JPEG 수신→이벤트 발생 |', '| Detection latency | ≤ 200ms | JPEG received → event triggered |'),
    ('| 오탐 (FPR) | ≤ 5% | 조명 변화·태양광 제외 |', '| False positive (FPR) | ≤ 5% | Excluding lighting changes / sunlight |'),
    ('| 화재 크기 | bbox ≥ 32×32px | 화재 초기 단계 포함 |', '| Fire size | bbox ≥ 32×32px | Including early stage fires |'),
    ('### 2.3 비기능 요구사항', '### 2.3 Non-Functional Requirements'),
    ('- 모델 포맷: ONNX (onnxruntime-node CPU/CUDA 호환)', '- Model format: ONNX (onnxruntime-node CPU/CUDA compatible)'),
    ('- 모델 크기: ≤ 100MB (서버 부담 최소화)', '- Model size: ≤ 100MB (minimize server load)'),
    ('- 서버 영향: 기존 파이프라인 추가 지연 ≤ 50ms', '- Server impact: additional latency to existing pipeline ≤ 50ms'),
    ('- 기존 로이터링 감지와 독립적으로 동작', '- Operates independently from existing loitering detection'),
    ('## 3. 모델 아키텍처', '## 3. Model Architecture'),
    ('### 3.1 채택 모델: YOLOv8s Fire & Smoke Detection', '### 3.1 Selected Model: YOLOv8s Fire & Smoke Detection'),
    ('입력: JPEG 프레임 (640×640 letter-box 전처리)', 'Input: JPEG frame (640×640 letterbox preprocessing)'),
    ('모델: YOLOv8s (small) — 3-class fine-tuned', 'Model: YOLOv8s (small) — 3-class fine-tuned'),
    ('출처: github.com/Abonia1/YOLOv8-Fire-and-Smoke-Detection', 'Source: github.com/Abonia1/YOLOv8-Fire-and-Smoke-Detection'),
    ('파일: server/models/yolov8s_fire_smoke.onnx  (43MB)', 'File: server/models/yolov8s_fire_smoke.onnx  (43MB)'),
    ('출력: [1, 7, 8400]  (4 bbox coords + 3 class scores × 8400 anchors)', 'Output: [1, 7, 8400]  (4 bbox coords + 3 class scores × 8400 anchors)'),
    ("클래스: Fire=0, default=1 (무시), smoke=2", "Classes: Fire=0, default=1 (skip), smoke=2"),
    ('### 3.2 후처리 파이프라인', '### 3.2 Post-processing Pipeline'),
    ('    ▼ sharp 전처리', '    ▼ sharp preprocessing'),
    ('  640×640 letterbox (fill=gray114, normalize /255)', '  640×640 letterbox (fill=gray114, normalize /255)'),
    ('    ▼ ONNX 추론', '    ▼ ONNX inference'),
    ('    ▼ 후처리', '    ▼ Post-processing'),
    ('  confidence filtering (>0.35)', '  confidence filtering (>0.35)'),
    ("  'default' 클래스 제거 (classIdx=1 skip)", "  remove 'default' class (classIdx=1 skip)"),
    ("  소문자 정규화 ('Fire' → 'fire')", "  lowercase normalization ('Fire' → 'fire')"),
    ('### 3.3 클래스 정의', '### 3.3 Class Definitions'),
    ('| Index | 원본 클래스명 | 내부 매핑 | 설명 | 표시 색상 |', '| Index | Original Class | Internal Mapping | Description | Display Color |'),
    ('| 0 | `Fire` | `fire` | 화염 (불꽃, 화재) | 🔴 주황-빨간 `rgba(255,80,0)` |',
     '| 0 | `Fire` | `fire` | Flames (fire) | 🔴 Orange-red `rgba(255,80,0)` |'),
    ('| 1 | `default` | *(skip)* | 미분류 — 후처리에서 제외 | — |',
     '| 1 | `default` | *(skip)* | Unclassified — excluded in post-processing | — |'),
    ('| 2 | `smoke` | `smoke` | 연기 (회색, 흑색 연기) | ⬜ 어두운 회색 `rgba(75,85,99)` |',
     '| 2 | `smoke` | `smoke` | Smoke (gray, black smoke) | ⬜ Dark gray `rgba(75,85,99)` |'),
    ('## 4. 공개 모델 소스', '## 4. Public Model Sources'),
    ('### 4.1 사용 모델 (현재 설치 기준)', '### 4.1 Models Used (current installation)'),
    ('| 순위 | 모델 | 소스 | ONNX 크기 | 클래스 | 비고 |', '| Rank | Model | Source | ONNX Size | Classes | Notes |'),
    ('| ✅ **채택** | YOLOv8s fire/smoke | Abonia1/YOLOv8-Fire-and-Smoke-Detection (GitHub) | 43MB | Fire, default, smoke | **현재 설치됨** |',
     '| ✅ **Selected** | YOLOv8s fire/smoke | Abonia1/YOLOv8-Fire-and-Smoke-Detection (GitHub) | 43MB | Fire, default, smoke | **Currently installed** |'),
    ('| — | YOLOv8m fire/smoke | keremberke/yolov8m-fire-and-smoke-detection (HuggingFace) | ~52MB | fire, smoke | 저장소 비공개로 다운로드 불가 |',
     '| — | YOLOv8m fire/smoke | keremberke/yolov8m-fire-and-smoke-detection (HuggingFace) | ~52MB | fire, smoke | Repository private, download unavailable |'),
    ('| — | YOLOv10 fire/smoke | TommyNgx/YOLOv10-Fire-and-Smoke-Detection (HuggingFace) | ~30MB | fire, smoke | 대안 후보 |',
     '| — | YOLOv10 fire/smoke | TommyNgx/YOLOv10-Fire-and-Smoke-Detection (HuggingFace) | ~30MB | fire, smoke | Alternative candidate |'),
    ('> **비고**: `keremberke` HuggingFace 저장소가 비공개(401 Unauthorized)로 전환됨. `Abonia1` GitHub 저장소의 학습 완료 가중치(`runs/detect/train/weights/best.pt`)를 ONNX 변환하여 적용.',
     '> **Note**: The `keremberke` HuggingFace repository has been set to private (401 Unauthorized). Applied by converting the trained weights (`runs/detect/train/weights/best.pt`) from the `Abonia1` GitHub repository to ONNX.'),
    ('### 4.2 학습 데이터셋', '### 4.2 Training Datasets'),
    ('| 데이터셋 | 규모 | 링크 |', '| Dataset | Size | Link |'),
    ('| D-Fire | 21,000+ 이미지 (fire/smoke/no-event) | GitHub: gaiasd/DFireDataset |',
     '| D-Fire | 21,000+ images (fire/smoke/no-event) | GitHub: gaiasd/DFireDataset |'),
    ('| VisiFire | 복합 실내외 화재 영상 | VisiFire.net |', '| VisiFire | Mixed indoor/outdoor fire video | VisiFire.net |'),
    ('| Foggia et al. | 야외/실내 화재 영상 | 학술 데이터셋 |', '| Foggia et al. | Outdoor/indoor fire video | Academic dataset |'),
    ('## 5. 구현 계획', '## 5. Implementation Plan'),
    ('### 5.1 서버 — FireSmokeService', '### 5.1 Server — FireSmokeService'),
    ('**파일**: `server/src/services/fireSmokeService.js`', '**File**: `server/src/services/fireSmokeService.js`'),
    ('  async load()                         // 모델 로드 (파일 없으면 graceful skip)',
     '  async load()                         // Load model (graceful skip if file missing)'),
    ('  get ready()                          // → boolean', '  get ready()                          // → boolean'),
    ('  async detect(jpegBuf, origW, origH)  // → [{className, confidence, bbox}]',
     '  async detect(jpegBuf, origW, origH)  // → [{className, confidence, bbox}]'),
    ('**파이프라인 통합 위치** (`pipelineManager.js`):', '**Pipeline integration point** (`pipelineManager.js`):'),
    ('1. JPEG 프레임 수신', '1. Receive JPEG frame'),
    ('2. Primary Detection (YOLOv8n COCO — person/vehicle)', '2. Primary Detection (YOLOv8n COCO — person/vehicle)'),
    ('3. ByteTracker → tracked objects', '3. ByteTracker → tracked objects'),
    ('4. BehaviorEngine → loitering analysis', '4. BehaviorEngine → loitering analysis'),
    ('5. AttributePipeline → face/mask/hat/color enrichment', '5. AttributePipeline → face/mask/hat/color enrichment'),
    ('6. ▶ FireSmokeService.detect() ← 여기 추가 (full-frame, 독립 실행)', '6. ▶ FireSmokeService.detect() ← added here (full-frame, independent execution)'),
    ('7. 결과 병합 → fire/smoke bbox를 detections 배열에 추가', '7. Merge results → add fire/smoke bbox to detections array'),
    ('8. Zone 교차 확인 → fire:alert 이벤트 발생', '8. Zone intersection check → fire:alert event triggered'),
    ('9. detections 소켓 emit', '9. Emit detections socket'),
    ('### 5.2 화재 경보 이벤트', '### 5.2 Fire Alert Event'),
    ('// Socket.IO 이벤트: \'fire:alert\'', "// Socket.IO event: 'fire:alert'"),
    ('### 5.3 클라이언트', '### 5.3 Client'),
    ('- **Zone Editor**: fire / smoke 체크박스 추가 (모델 존재 시 활성화)', '- **Zone Editor**: Add fire / smoke checkboxes (enabled when model exists)'),
    ('- **CameraView 오버레이**: fire=주황-빨간 bbox, smoke=회색 bbox + 배경 오버레이',
     '- **CameraView overlay**: fire=orange-red bbox, smoke=gray bbox + background overlay'),
    ('- **FullscreenView DetectionPanel**: fire/smoke 항목 적색/회색 강조', '- **FullscreenView DetectionPanel**: fire/smoke items highlighted in red/gray'),
    ('- **범례**: ■ fire (주황), ■ smoke (회색) 추가', '- **Legend**: ■ fire (orange), ■ smoke (gray) added'),
    ('### 5.4 모델 설치 절차 (완료)', '### 5.4 Model Installation Procedure (Complete)'),
    ('현재 `server/models/yolov8s_fire_smoke.onnx` (43MB)가 설치되어 있습니다.',
     'Currently `server/models/yolov8s_fire_smoke.onnx` (43MB) is installed.'),
    ('재설치가 필요한 경우 아래 스크립트를 실행합니다 (Python 3.7+, ultralytics 필요):',
     'If reinstallation is needed, run the script below (requires Python 3.7+, ultralytics):'),
    ('# 1. GitHub에서 학습 완료 가중치 다운로드', '# 1. Download trained weights from GitHub'),
    ('# 2. ONNX 변환 (Python 3.7 + ultralytics 8.x)', '# 2. Convert to ONNX (Python 3.7 + ultralytics 8.x)'),
    ('# 클래스: {0: \'Fire\', 1: \'default\', 2: \'smoke\'}', "# Classes: {0: 'Fire', 1: 'default', 2: 'smoke'}"),
    ('> **주의**: 모델 출력이 `[1, 7, 8400]` (3-class)이므로 `fireSmokeService.js`의 `CLASS_NAMES = [\'fire\', \'default\', \'smoke\']`와 `SKIP_CLASSES`가 맞춰져 있어야 합니다.',
     "> **Note**: Since the model output is `[1, 7, 8400]` (3-class), `fireSmokeService.js` must have `CLASS_NAMES = ['fire', 'default', 'smoke']` and `SKIP_CLASSES` aligned."),
    ('## 6. 엔드포인트 및 이벤트', '## 6. Endpoints and Events'),
    ('### 6.1 기존 엔드포인트 변경', '### 6.1 Existing Endpoint Changes'),
    ('| 엔드포인트 | 변경 내용 |', '| Endpoint | Change |'),
    ('| `GET /api/capabilities` | `ai.fire`, `ai.smoke` 필드 추가 |', '| `GET /api/capabilities` | Added `ai.fire`, `ai.smoke` fields |'),
    ('| `GET /health` | 변경 없음 |', '| `GET /health` | No change |'),
    ('### 6.2 새 Socket.IO 이벤트', '### 6.2 New Socket.IO Events'),
    ('| 이벤트 | 방향 | 페이로드 |', '| Event | Direction | Payload |'),
    ('| `fire:alert` | Server→Client | `{cameraId, className, confidence, zone, timestamp}` |',
     '| `fire:alert` | Server→Client | `{cameraId, className, confidence, zone, timestamp}` |'),
    ('## 7. 성능 최적화', '## 7. Performance Optimization'),
    ('| 최적화 | 방법 |', '| Optimization | Method |'),
    ('| 프레임 스킵 | 기존 `_inferring` guard와 동일한 frame-drop 처리 |',
     '| Frame skip | Same frame-drop processing as existing `_inferring` guard |'),
    ('| Zone 필터링 | `targetClasses`에 fire/smoke 없으면 탐지 건너뜀 |',
     '| Zone filtering | Skip detection if fire/smoke not in `targetClasses` |'),
    ('| 모델 크기 | YOLOv8s 43MB (ONNX 설치 완료) |', '| Model size | YOLOv8s 43MB (ONNX installed) |'),
    ('| 알림 쿨다운 | 동일 Zone 동일 클래스 경보는 10초 간격으로 제한 (중복 방지) |',
     '| Alert cooldown | Alerts for same zone same class limited to 10-second intervals (deduplication) |'),
    ("| default 클래스 스킵 | 후처리에서 classIdx=1 제외 — 불필요한 감지 억제 |",
     '| Default class skip | classIdx=1 excluded in post-processing — suppresses unnecessary detections |'),
    ('## 8. 구현 이력', '## 8. Implementation History'),
    ('| 날짜 | 내용 |', '| Date | Description |'),
    ('| 2026-05-18 | `fireSmokeService.js` 구현 완료 |', '| 2026-05-18 | `fireSmokeService.js` implementation complete |'),
    ('| 2026-05-18 | `yolov8s_fire_smoke.onnx` (43MB) 설치 — Abonia1/GitHub |', '| 2026-05-18 | `yolov8s_fire_smoke.onnx` (43MB) installed — Abonia1/GitHub |'),
    ('| 2026-05-18 | 3-class 모델 대응: `CLASS_NAMES`, `SKIP_CLASSES`, `NORMALISE` 추가 |',
     '| 2026-05-18 | 3-class model support: added `CLASS_NAMES`, `SKIP_CLASSES`, `NORMALISE` |'),
    ('| 2026-05-18 | 서버 재시작 후 `[FireSmokeService] yolov8s_fire_smoke.onnx loaded` 확인 |',
     '| 2026-05-18 | Confirmed `[FireSmokeService] yolov8s_fire_smoke.onnx loaded` after server restart |'),
    ('## 9. 테스트 계획', '## 9. Test Plan'),
    ('| 테스트 | 방법 | 합격 기준 | 상태 |', '| Test | Method | Pass Criteria | Status |'),
    ('| 모델 로드 | 서버 시작 로그 확인 | `loaded` 메시지 출력 | ✅ |', '| Model load | Check server startup log | `loaded` message output | ✅ |'),
    ('| 기능 | 화재 영상 재생 → fire:alert 발생 확인 | 10초 내 경보 | 🔲 |', '| Functional | Play fire video → verify fire:alert | Alert within 10 seconds | 🔲 |'),
    ('| 정밀도 | D-Fire test set 추론 | mAP@0.5 ≥ 0.80 | 🔲 |', '| Precision | D-Fire test set inference | mAP@0.5 ≥ 0.80 | 🔲 |'),
    ('| 성능 | CPU 단독 640×640 추론 속도 | ≥ 10 FPS | 🔲 |', '| Performance | CPU-only 640×640 inference speed | ≥ 10 FPS | 🔲 |'),
    ('| 오탐 | 일반 실내/외 영상 24시간 | FPR ≤ 5% | 🔲 |', '| False positive | 24-hour general indoor/outdoor video | FPR ≤ 5% | 🔲 |'),
    ('| 통합 | 로이터링 감지와 동시 동작 | 파이프라인 지연 ≤ 50ms | 🔲 |', '| Integration | Simultaneous operation with loitering detection | Pipeline delay ≤ 50ms | 🔲 |'),
    ('## 9. 관련 문서', '## 9. Related Documents'),
    ('*이 문서는 LTS(Loitering Tracking System) AI 모듈 RFP 시리즈의 일부입니다.*',
     '*This document is part of the LTS (Loitering Tracking System) AI module RFP series.*'),
]

result = translate_file(f'{BASE}/RFP_AI_Fire_Smoke_Detection.md', fire_smoke_replacements)
print(f"RFP_AI_Fire_Smoke_Detection.md: {'updated' if result else 'no changes'}")

# ============================================================
# RFP_AI_Cloth_Analysis.md
# ============================================================
cloth_replacements = [
    ('| **Status** | **Phase-1 구현 완료 (색상 공유) / Phase-2 PAR 준비중** |',
     '| **Status** | **Phase-1 Implemented (color sharing) / Phase-2 PAR Pending** |'),
    # Korean clothing category names in tables
    ('"description": "후드티, 청바지"', '"description": "hoodie, jeans"'),
    ('| 0 | t-shirt | 티셔츠 | Short sleeve, round neck |', '| 0 | t-shirt | T-shirt | Short sleeve, round neck |'),
    ('| 1 | shirt | 셔츠 | Button-down, dress shirt |', '| 1 | shirt | Shirt | Button-down, dress shirt |'),
    ('| 2 | hoodie | 후드티 | Pullover/zip hoodie |', '| 2 | hoodie | Hoodie | Pullover/zip hoodie |'),
    ('| 3 | sweater | 스웨터 | Knit, pullover, crewneck |', '| 3 | sweater | Sweater | Knit, pullover, crewneck |'),
    ('| 4 | jacket | 재킷 | Blazer, denim, bomber |', '| 4 | jacket | Jacket | Blazer, denim, bomber |'),
    ('| 5 | coat | 코트 | Long coat, overcoat, trench |', '| 5 | coat | Coat | Long coat, overcoat, trench |'),
    ('| 6 | vest | 조끼 | Waistcoat, sleeveless |', '| 6 | vest | Vest | Waistcoat, sleeveless |'),
    ('| 7 | uniform_top | 유니폼 상의 | Work/school uniform |', '| 7 | uniform_top | Uniform top | Work/school uniform |'),
    ('| 0 | jeans | 청바지 | Denim jeans |', '| 0 | jeans | Jeans | Denim jeans |'),
    ('| 1 | trousers | 바지 | Chinos, slacks, dress pants |', '| 1 | trousers | Trousers | Chinos, slacks, dress pants |'),
    ('| 2 | shorts | 반바지 | Short pants |', '| 2 | shorts | Shorts | Short pants |'),
    ('| 3 | skirt | 치마 | Mini, midi, maxi skirt |', '| 3 | skirt | Skirt | Mini, midi, maxi skirt |'),
    ('| 4 | leggings | 레깅스 | Athletic, tight leggings |', '| 4 | leggings | Leggings | Athletic, tight leggings |'),
    ('| 5 | uniform_bottom | 유니폼 하의 | Work/school uniform bottom |', '| 5 | uniform_bottom | Uniform bottom | Work/school uniform bottom |'),
    ('| 0 | dress | 원피스 | Casual, formal dress |', '| 0 | dress | Dress | Casual, formal dress |'),
    ('| 1 | jumpsuit | 점프수트 | Overalls, boilersuit |', '| 1 | jumpsuit | Jumpsuit | Overalls, boilersuit |'),
    ('| 2 | suit | 정장 | Business suit (jacket + pants) |', '| 2 | suit | Suit | Business suit (jacket + pants) |'),
    ('| 3 | uniform_full | 전체 유니폼 | Security, medical, police |', '| 3 | uniform_full | Full uniform | Security, medical, police |'),
    ('| 4 | sportswear | 운동복 | Tracksuit, athletic set |', '| 4 | sportswear | Sportswear | Tracksuit, athletic set |'),
]

result = translate_file(f'{BASE}/RFP_AI_Cloth_Analysis.md', cloth_replacements)
print(f"RFP_AI_Cloth_Analysis.md: {'updated' if result else 'no changes'}")

# ============================================================
# RFP_AI_Color_Analysis.md
# ============================================================
color_replacements = [
    ('| **Status** | **Phase-1 구현 완료 (RGB 색상 추출) / Phase-2 PAR 준비중** |',
     '| **Status** | **Phase-1 Implemented (RGB color extraction) / Phase-2 PAR Pending** |'),
    # Color table Korean names
    ('| 0 | black | 검정 | #1a1a1a |', '| 0 | black | Black | #1a1a1a |'),
    ('| 1 | white | 흰색 | #f5f5f5 |', '| 1 | white | White | #f5f5f5 |'),
    ('| 2 | gray | 회색 | #808080 |', '| 2 | gray | Gray | #808080 |'),
    ('| 3 | red | 빨강 | #e53935 |', '| 3 | red | Red | #e53935 |'),
    ('| 4 | orange | 주황 | #fb8c00 |', '| 4 | orange | Orange | #fb8c00 |'),
    ('| 5 | yellow | 노랑 | #fdd835 |', '| 5 | yellow | Yellow | #fdd835 |'),
    ('| 6 | green | 초록 | #43a047 |', '| 6 | green | Green | #43a047 |'),
    ('| 7 | blue | 파랑 | #1e88e5 |', '| 7 | blue | Blue | #1e88e5 |'),
    ('| 8 | purple | 보라 | #8e24aa |', '| 8 | purple | Purple | #8e24aa |'),
    ('| 9 | pink | 분홍 | #f06292 |', '| 9 | pink | Pink | #f06292 |'),
    ('| 10 | brown | 갈색 | #6d4c41 |', '| 10 | brown | Brown | #6d4c41 |'),
    ('| 11 | navy | 남색 | Dark blue |', '| 11 | navy | Navy | Dark blue |'),
    ('| 12 | beige | 베이지 | Light tan |', '| 12 | beige | Beige | Light tan |'),
    ('| 13 | khaki | 카키 | Military green-tan |', '| 13 | khaki | Khaki | Military green-tan |'),
    ('| 14 | cyan | 청록 | Blue-green |', '| 14 | cyan | Cyan | Blue-green |'),
    ('| 15 | silver | 은색 | Metallic gray |', '| 15 | silver | Silver | Metallic gray |'),
    ('| 16 | gold | 금색 | Metallic yellow |', '| 16 | gold | Gold | Metallic yellow |'),
    ('| 17 | multicolor | 다색 | Complex patterns |', '| 17 | multicolor | Multicolor | Complex patterns |'),
]

result = translate_file(f'{BASE}/RFP_AI_Color_Analysis.md', color_replacements)
print(f"RFP_AI_Color_Analysis.md: {'updated' if result else 'no changes'}")

# ============================================================
# RFP_AI_Accessories_Detection.md
# ============================================================
accessories_replacements = [
    # Korean in extended categories table
    ('| `shopping_bag` | 쇼핑백 | Retail environment |', '| `shopping_bag` | Shopping bag | Retail environment |'),
    ('| `sports_bag` | 스포츠백 | Athletic facility |', '| `sports_bag` | Sports bag | Athletic facility |'),
    ('| `camera` | 카메라 | Tourist/surveillance context |', '| `camera` | Camera | Tourist/surveillance context |'),
    ('| `phone` | 핸드폰 | Person interaction context |', '| `phone` | Phone | Person interaction context |'),
    ('| `weapon_shape` | 형태적 위협물 | Security trigger (long object, etc.) |', '| `weapon_shape` | Threat-shaped object | Security trigger (long object, etc.) |'),
    ('| `stroller` | 유모차 | Family zone monitoring |', '| `stroller` | Stroller | Family zone monitoring |'),
]

result = translate_file(f'{BASE}/RFP_AI_Accessories_Detection.md', accessories_replacements)
print(f"RFP_AI_Accessories_Detection.md: {'updated' if result else 'no changes'}")

print("Phase 1 complete.")
