import re

def translate_file(filepath, replacements):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    original = content
    for korean, english in replacements:
        content = content.replace(korean, english)
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False

BASE = '/home/youngho/workspace/loitering_tracking'

# ============================================================
# RFP_Dashboard_Sidebar_Cameras.md
# ============================================================
cameras_replacements = [
    ('# RFP: Dashboard Sidebar — Cameras 패널', '# RFP: Dashboard Sidebar — Cameras Panel'),
    ('**Status**: Phase-1 구현 기준 작성', '**Status**: Written based on Phase-1 implementation'),

    ('## 목차', '## Table of Contents'),
    ('1. [개요](#1-개요)', '1. [Overview](#1-overview)'),
    ('2. [패널 구성도](#2-패널-구성도)', '2. [Panel Diagram](#2-panel-diagram)'),
    ('3. [패널 헤더](#3-패널-헤더)', '3. [Panel Header](#3-panel-header)'),
    ('4. [서브 탭 구조 (Added / Found)](#4-서브-탭-구조-added--found)', '4. [Sub-Tab Structure (Added / Found)](#4-sub-tab-structure-added--found)'),
    ('5. [Added 탭 — 등록된 카메라 목록](#5-added-탭--등록된-카메라-목록)', '5. [Added Tab — Registered Camera List](#5-added-tab--registered-camera-list)'),
    ('6. [Found 탭 — 자동 탐색 카메라 목록](#6-found-탭--자동-탐색-카메라-목록)', '6. [Found Tab — Auto-discovered Camera List](#6-found-tab--auto-discovered-camera-list)'),
    ('7. [카메라 추가 Modal](#7-카메라-추가-modal)', '7. [Camera Add Modal](#7-camera-add-modal)'),
    ('8. [카메라 편집 Modal (CameraEditModal)](#8-카메라-편집-modal-cameraeditmodal)', '8. [Camera Edit Modal (CameraEditModal)](#8-camera-edit-modal-cameraeditmodal)'),
    ('9. [Discovered Camera Panel (오버레이)](#9-discovered-camera-panel-오버레이)', '9. [Discovered Camera Panel (Overlay)](#9-discovered-camera-panel-overlay)'),
    ('10. [REST API 연동](#10-rest-api-연동)', '10. [REST API Integration](#10-rest-api-integration)'),
    ('11. [상태 관리](#11-상태-관리)', '11. [State Management](#11-state-management)'),
    ('12. [구현 현황](#12-구현-현황)', '12. [Implementation Status](#12-implementation-status)'),

    # Section 1
    ('## 1. 개요', '## 1. Overview'),
    ('### 1.1 목적\n\n본 문서는 LTS Dashboard 우측 Sidebar의 **Cameras 탭** 패널에 대한 기술 요구사항을 정의한다. Cameras 패널은 시스템에 등록된 IP 카메라 및 YouTube 가상 채널 목록을 표시하고, ONVIF/WiseNet UDP 프로토콜로 자동 탐색된 카메라를 관리하는 기능을 담당한다.',
     '### 1.1 Purpose\n\nThis document defines the technical requirements for the **Cameras tab** panel of the LTS Dashboard right sidebar. The Cameras panel is responsible for displaying the list of IP cameras and YouTube virtual channels registered in the system, and managing cameras auto-discovered via ONVIF/WiseNet UDP protocols.'),
    ('### 1.2 범위\n\n- Added 탭: 등록된 카메라 목록, 상태 표시, 선택/재연결/편집/삭제 \n- Found 탭: 자동 탐색 카메라 목록, 검색 필터, 상세 오버레이\n- 카메라 수동 추가 Modal (RTSP / YouTube)\n- 카메라 편집 Modal\n- Discovered Camera Panel 오버레이',
     '### 1.2 Scope\n\n- Added tab: Registered camera list, status display, select/reconnect/edit/delete\n- Found tab: Auto-discovered camera list, search filter, detail overlay\n- Manual camera add Modal (RTSP / YouTube)\n- Camera edit Modal\n- Discovered Camera Panel overlay'),

    # Section 2
    ('## 2. 패널 구성도', '## 2. Panel Diagram'),
    ('### 2.1 전체 레이아웃', '### 2.1 Full Layout'),
    ('│  Cameras  ●  [+ Add]            │  ← 헤더 (flex, border-b)',
     '│  Cameras  ●  [+ Add]            │  ← Header (flex, border-b)'),
    ('│  [Added (N)]  [Found (N)]        │  ← 서브 탭', '│  [Added (N)]  [Found (N)]        │  ← Sub-tabs'),
    ('│  │ ● CameraName          ✎ ↺ ✕ ││  ← 카메라 행 (Added 탭)',
     '│  │ ● CameraName          ✎ ↺ ✕ ││  ← Camera row (Added tab)'),
    ('│  │ ● CameraName   [YT] ✎ ↺ ✕  ││', '│  │ ● CameraName   [YT] ✎ ↺ ✕  ││'),
    ('[Found 탭 선택 시]', '[When Found tab selected]'),
    ('│  Scanning… [●]       [Clean]    │  ← Found 헤더', '│  Scanning… [●]       [Clean]    │  ← Found header'),
    ('│  🔍 [Model, IP, MAC, port...]    │  ← 검색 바', '│  🔍 [Model, IP, MAC, port...]    │  ← Search bar'),

    # Section 3
    ('## 3. 패널 헤더', '## 3. Panel Header'),
    ('### 3.1 구성 요소', '### 3.1 Components'),
    ('| 요소 | 설명 | CSS |', '| Element | Description | CSS |'),
    ('| **제목** | `"Cameras"` (고정 텍스트) | `text-sm font-bold text-white` |',
     '| **Title** | `"Cameras"` (fixed text) | `text-sm font-bold text-white` |'),
    ('| **연결 상태 점** | Socket.IO 연결 여부 | `w-2 h-2 rounded-full` + 색상 |',
     '| **Connection status dot** | Socket.IO connection state | `w-2 h-2 rounded-full` + color |'),
    ('| **+ Add 버튼** | 카메라 추가 Modal 열기 | `bg-green-700 hover:bg-green-600 text-white text-[11px]` |',
     '| **+ Add button** | Open camera add Modal | `bg-green-700 hover:bg-green-600 text-white text-[11px]` |'),
    ('### 3.2 연결 상태 점', '### 3.2 Connection Status Dot'),
    ('| 상태 | 색상 | 애니메이션 |', '| State | Color | Animation |'),
    ('| 연결됨 | `bg-green-500` | `animate-pulse` |', '| Connected | `bg-green-500` | `animate-pulse` |'),
    ('| 연결 안 됨 | `bg-red-500` | 없음 |', '| Disconnected | `bg-red-500` | None |'),

    # Section 4
    ('## 4. 서브 탭 구조 (Added / Found)', '## 4. Sub-Tab Structure (Added / Found)'),
    ('### 4.1 탭 버튼', '### 4.1 Tab Buttons'),
    ('| 탭 | 표시 | 카운트 |', '| Tab | Display | Count |'),
    ('| `added` | `Added (N)` | 등록된 카메라 수 |', '| `added` | `Added (N)` | Number of registered cameras |'),
    ('| `found` | `Found (N)` | 탐색된 기기 수 |', '| `found` | `Found (N)` | Number of discovered devices |'),
    ('- 활성 탭: `text-blue-400 border-b-2 border-blue-400`', '- Active tab: `text-blue-400 border-b-2 border-blue-400`'),
    ('- 비활성 탭: `text-gray-500 hover:text-gray-300`', '- Inactive tab: `text-gray-500 hover:text-gray-300`'),
    ('### 4.2 Found 탭 스캔 중 표시', '### 4.2 Found Tab Scanning Indicator'),
    ('스캐닝 중일 때 Found 탭 레이블 왼쪽에 파란 애니메이션 점 표시.',
     'Blue animated dot displayed to the left of the Found tab label while scanning.'),
    ('### 4.3 자동 탭 전환', '### 4.3 Auto Tab Switch'),
    ('서버에서 첫 번째 탐색 기기(`discovery:result` 이벤트)가 수신되면 **Found 탭으로 자동 전환** (`autoSwitched` 플래그로 1회 한정).',
     'When the first discovered device (`discovery:result` event) is received from the server, **automatically switches to the Found tab** (limited to once via `autoSwitched` flag).'),

    # Section 5
    ('## 5. Added 탭 — 등록된 카메라 목록', '## 5. Added Tab — Registered Camera List'),
    ('### 5.1 빈 목록 상태', '### 5.1 Empty List State'),
    ('등록된 카메라가 없을 경우:', 'When there are no registered cameras:'),
    ('### 5.2 카메라 행 구조', '### 5.2 Camera Row Structure'),
    ('│  [●]  CameraName          [✎] [↺] [✕]     │  ← RTSP 카메라',
     '│  [●]  CameraName          [✎] [↺] [✕]     │  ← RTSP camera'),
    ('│  [●]  CameraName  [YT]   [✎] [↺] [✕]     │  ← YouTube 채널',
     '│  [●]  CameraName  [YT]   [✎] [↺] [✕]     │  ← YouTube channel'),
    ('| **StatusDot** | 좌측 상태 색상 원 |', '| **StatusDot** | Left-side status color circle |'),
    ('| **카메라 이름** | `text-xs font-semibold text-white truncate` |',
     '| **Camera name** | `text-xs font-semibold text-white truncate` |'),
    ('| **YT 뱃지** | YouTube 채널일 때만 표시. `bg-red-700 text-white text-[9px]` |',
     '| **YT badge** | Shown only for YouTube channels. `bg-red-700 text-white text-[9px]` |'),
    ('| **서브 정보 행** | 이름 아래 `text-[10px] text-gray-400 truncate` — 타입에 따라 다름 (§5.2.1) |',
     '| **Sub info row** | `text-[10px] text-gray-400 truncate` below name — varies by type (§5.2.1) |'),
    ('| **액션 버튼 그룹** | 호버 시에만 표시 (`opacity-0 group-hover:opacity-100`) |',
     '| **Action button group** | Shown on hover only (`opacity-0 group-hover:opacity-100`) |'),
    ('#### 5.2.1 서브 정보 행 — 타입별 표시 규칙', '#### 5.2.1 Sub Info Row — Display Rules by Type'),
    ('카메라 이름 아래 두 번째 줄은 카메라 타입에 따라 다른 정보를 표시한다.',
     'The second line below the camera name displays different information depending on camera type.'),
    ('| 카메라 타입 | 서브 정보 | 조건 |', '| Camera type | Sub info | Condition |'),
    ('| **RTSP** (`type !== \'youtube\'`) | `cam.ip` — IP 주소 | `cam.ip` 가 존재할 때만 표시 |',
     '| **RTSP** (`type !== \'youtube\'`) | `cam.ip` — IP address | Shown only when `cam.ip` exists |'),
    ('| **YouTube** (`type === \'youtube\'`) | `cam.youtubeUrl` — 원본 YouTube URL | `cam.youtubeUrl` 이 존재할 때만 표시 |',
     '| **YouTube** (`type === \'youtube\'`) | `cam.youtubeUrl` — Original YouTube URL | Shown only when `cam.youtubeUrl` exists |'),
    ('- YouTube URL 호버 툴팁: `title={cam.youtubeUrl}` 로 전체 URL 확인 가능',
     '- YouTube URL hover tooltip: full URL viewable via `title={cam.youtubeUrl}`'),
    ('- 예시:', '- Examples:'),
    ('#### 5.2.1 StatusDot 색상 사양', '#### 5.2.1 StatusDot Color Specification'),
    ('| 카메라 상태 | 색상 | HEX |', '| Camera status | Color | HEX |'),
    ('| `live` | 녹색 | `bg-green-500` |', '| `live` | Green | `bg-green-500` |'),
    ('| `error` | 빨강 | `bg-red-500` |', '| `error` | Red | `bg-red-500` |'),
    ('| `offline` | 회색 | `bg-gray-500` |', '| `offline` | Gray | `bg-gray-500` |'),
    ('| `connecting`, `streaming`, `reconnecting`, `idle` | 노랑 | `bg-yellow-500` |',
     '| `connecting`, `streaming`, `reconnecting`, `idle` | Yellow | `bg-yellow-500` |'),
    ('#### 5.2.2 액션 버튼 사양', '#### 5.2.2 Action Button Specification'),
    ('| 버튼 | 아이콘 | 동작 | 호버 색상 |', '| Button | Icon | Behavior | Hover color |'),
    ('| 편집 | `✎` | `CameraEditModal` 열기 | `hover:text-blue-400` |',
     '| Edit | `✎` | Open `CameraEditModal` | `hover:text-blue-400` |'),
    ('| 재연결 | `↺` | `/api/cameras/{id}/stream/reconnect` POST | `hover:text-yellow-400` |',
     '| Reconnect | `↺` | `/api/cameras/{id}/stream/reconnect` POST | `hover:text-yellow-400` |'),
    ('| 삭제 | `✕` | 확인창 → `/api/cameras/{id}` DELETE | `hover:text-red-400` |',
     '| Delete | `✕` | Confirm dialog → `/api/cameras/{id}` DELETE | `hover:text-red-400` |'),
    ('#### 5.2.3 재연결 중 상태', '#### 5.2.3 Reconnecting State'),
    ('재연결 요청 후 2초간 `"Reconnecting…"` 텍스트 표시:',
     'Shows `"Reconnecting…"` text for 2 seconds after reconnect request:'),
    ('### 5.3 클릭 동작', '### 5.3 Click Behavior'),
    ('| **싱글 클릭** | 카메라 선택 (CameraStore의 `selectedId` 변경) |',
     '| **Single click** | Select camera (change `selectedId` in CameraStore) |'),
    ('| **더블클릭** | 카메라 재연결 요청 (300ms 딜레이로 싱글/더블 구분) |',
     '| **Double-click** | Camera reconnect request (single/double distinguished by 300ms delay) |'),
    ('| **우클릭 (컨텍스트 메뉴)** | `CameraEditModal` 직접 열기 |',
     '| **Right-click (context menu)** | Open `CameraEditModal` directly |'),
    ('### 5.4 선택된 카메라 행 스타일', '### 5.4 Selected Camera Row Style'),
    ('### 5.5 미선택 카메라 행 스타일', '### 5.5 Unselected Camera Row Style'),

    # Section 6
    ('## 6. Found 탭 — 자동 탐색 카메라 목록', '## 6. Found Tab — Auto-discovered Camera List'),
    ('### 6.1 Found 헤더 바', '### 6.1 Found Header Bar'),
    ('│  [● Scanning…] or [N device(s) found]   [Clean] │', '│  [● Scanning…] or [N device(s) found]   [Clean] │'),
    ('| 스캔 중 | `● Scanning…` (파란 점 ping 애니메이션) |', '| Scanning | `● Scanning…` (blue dot ping animation) |'),
    ('| 스캔 완료 | `N device(s) found` (회색 텍스트) |', '| Scan complete | `N device(s) found` (gray text) |'),
    ('| 기기 없음 | `Waiting…` |', '| No devices | `Waiting…` |'),
    ('**Clean 버튼**: 탐색 결과 초기화 + `discovery:rescan` Socket 이벤트 발송',
     '**Clean button**: Reset discovery results + send `discovery:rescan` Socket event'),
    ('### 6.2 검색 바', '### 6.2 Search Bar'),
    ('#### 6.2.1 검색 대상 필드', '#### 6.2.1 Searchable Fields'),
    ('| 필드 키 | 표시 레이블 |', '| Field key | Display label |'),
    ('#### 6.2.2 가상 카테고리 검색', '#### 6.2.2 Virtual Category Search'),
    ('문자열 검색 외에 boolean/enum 필드에 대한 키워드 매칭 지원:',
     'In addition to string search, supports keyword matching for boolean/enum fields:'),
    ('| 키워드 | 매칭 조건 | 레이블 |', '| Keyword | Match condition | Label |'),
    ('| `onvif` | `SupportOnvif=true` 또는 `source=onvif/both` | ONVIF |',
     '| `onvif` | `SupportOnvif=true` or `source=onvif/both` | ONVIF |'),
    ('| `sunapi`, `wisenet`, `hanwha` | `SupportSunapi=true` | SUNAPI |',
     '| `sunapi`, `wisenet`, `hanwha` | `SupportSunapi=true` | SUNAPI |'),
    ('| `udp`, `wisenet`, `hanwha` | `source=udp/both` | WiseNet |',
     '| `udp`, `wisenet`, `hanwha` | `source=udp/both` | WiseNet |'),
    ('#### 6.2.3 검색 결과 카운트', '#### 6.2.3 Search Result Count'),
    ('검색어 입력 시 하단에 `N / M match` 표시:', 'Displays `N / M match` at bottom when search query entered:'),
    ('#### 6.2.4 X 버튼 (검색어 초기화)', '#### 6.2.4 X Button (Clear Search)'),
    ('검색어가 있을 때만 오른쪽 끝에 표시. 클릭 시 `searchQuery = \'\'`.',
     'Shown at right end only when search query exists. Click sets `searchQuery = \'\'`.'),
    ('### 6.3 탐색 기기 행 구조', '### 6.3 Discovered Device Row Structure'),
    ('│  [●] DeviceName                [SUNAPI]     │', '│  [●] DeviceName                [SUNAPI]     │'),
    ('│      Manufacturer · IPAddress  [ONVIF]      │', '│      Manufacturer · IPAddress  [ONVIF]      │'),
    ('│      [match 뱃지] [match 뱃지]              │', '│      [match badge] [match badge]            │'),
    ('| **파란 점** | `w-1.5 h-1.5 rounded-full bg-blue-400` |', '| **Blue dot** | `w-1.5 h-1.5 rounded-full bg-blue-400` |'),
    ('| **기기 이름** | `Model` 없으면 `IPAddress` 표시 |', '| **Device name** | Shows `IPAddress` if no `Model` |'),
    ('| **서브텍스트** | `Manufacturer · IPAddress` |', '| **Sub-text** | `Manufacturer · IPAddress` |'),
    ('| **매칭 필드 뱃지** | 검색어와 매칭된 필드명 (노란 뱃지) |',
     '| **Matching field badges** | Field names matched to search query (yellow badge) |'),
    ('#### 6.3.1 뱃지 표시 조건', '#### 6.3.1 Badge Display Conditions'),
    ('### 6.4 탐색 기기 클릭 동작', '### 6.4 Discovered Device Click Behavior'),
    ('클릭 시 `DiscoveryStore.select(cam)` 호출 → `DiscoveredCameraPanel` 오버레이 표시.  \n이미 선택된 기기 재클릭 시 선택 해제.',
     'Click calls `DiscoveryStore.select(cam)` → shows `DiscoveredCameraPanel` overlay.  \nRe-clicking an already selected device deselects it.'),

    # Section 7
    ('## 7. 카메라 추가 Modal', '## 7. Camera Add Modal'),
    ('헤더의 **+ Add** 버튼 클릭 시 표시. `fixed inset-0 z-50 bg-black/70` 오버레이.',
     'Displayed on **+ Add** button click in header. `fixed inset-0 z-50 bg-black/70` overlay.'),
    ('### 7.1 소스 타입 선택', '### 7.1 Source Type Selection'),
    ('Modal 상단에서 추가 방식 선택:', 'Select the addition method at the top of the Modal:'),
    ('| `rtsp` | RTSP / ONVIF | IP 카메라 수동 추가 |', '| `rtsp` | RTSP / ONVIF | Manual IP camera addition |'),
    ('| `youtube` | YouTube | YouTube 스트림 가상 채널 추가 |', '| `youtube` | YouTube | Add YouTube stream virtual channel |'),
    ('### 7.2 RTSP 카메라 추가 폼', '### 7.2 RTSP Camera Add Form'),
    ('| 필드 | 타입 | 필수 | 설명 |', '| Field | Type | Required | Description |'),
    ('| Name | text | ✅ | 카메라 표시명 |', '| Name | text | ✅ | Camera display name |'),
    ('| RTSP URL | text | ✅ | `rtsp://...` 형식 |', '| RTSP URL | text | ✅ | `rtsp://...` format |'),
    ('| Username | text | ❌ | RTSP 인증 아이디 |', '| Username | text | ❌ | RTSP auth username |'),
    ('| Password | password | ❌ | RTSP 인증 비밀번호 |', '| Password | password | ❌ | RTSP auth password |'),
    ('| WebRTC Enabled | checkbox/toggle | ❌ | mediasoup WebRTC 스트림 사용 여부 |',
     '| WebRTC Enabled | checkbox/toggle | ❌ | Whether to use mediasoup WebRTC stream |'),
    ('**WebRTC Enabled 토글**: 기본값 `false`. 활성화 시 서버에서 `RtpIngestion` + mediasoup 파이프라인 사용.',
     '**WebRTC Enabled toggle**: Default `false`. When enabled, server uses `RtpIngestion` + mediasoup pipeline.'),
    ('**성공 시**: `CameraStore.addCamera()` 호출 → Added 탭으로 전환',
     '**On success**: Calls `CameraStore.addCamera()` → switch to Added tab'),
    ('#### 7.2.1 에러 처리', '#### 7.2.1 Error Handling'),
    ('| 이름 또는 URL 미입력 | `"Name and RTSP URL are required."` |',
     '| Name or URL not entered | `"Name and RTSP URL are required."` |'),
    ('| API 오류 | 서버 응답 메시지 |', '| API error | Server response message |'),
    ('### 7.3 YouTube 채널 추가 폼', '### 7.3 YouTube Channel Add Form'),
    ('| 필드 | 타입 | 필수 | 기본값 | 설명 |', '| Field | Type | Required | Default | Description |'),
    ('| Channel Name | text | ✅ | — | 채널 표시명 |', '| Channel Name | text | ✅ | — | Channel display name |'),
    ('| YouTube URL | text | ✅ | — | YouTube 페이지 URL |', '| YouTube URL | text | ✅ | — | YouTube page URL |'),
    ('| Resolution | select | ✅ | `1080p` | `1080p` / `720p` / `480p` |',
     '| Resolution | select | ✅ | `1080p` | `1080p` / `720p` / `480p` |'),
    ('| Bitrate | number | ✅ | `2000` | kbps |', '| Bitrate | number | ✅ | `2000` | kbps |'),
    ('| 반복 재생 | checkbox | ❌ | `false` | 영상 종료 시 자동 재시작 여부 (`repeatPlayback`) |',
     '| Repeat Playback | checkbox | ❌ | `false` | Auto-restart when video ends (`repeatPlayback`) |'),
    ('**반복 재생 동작**: 체크박스 활성화 시, YouTube 영상이 정상 종료(FFmpeg exit code 0)되면 재시작 카운터를 초기화하고 즉시 재시작. MAX_RESTARTS(5회) 제한을 우회하여 무한 반복 재생.',
     '**Repeat Playback behavior**: When checkbox enabled, if the YouTube video ends normally (FFmpeg exit code 0), the restart counter is reset and the video immediately restarts. Bypasses the MAX_RESTARTS(5) limit for infinite loop playback.'),
    ('#### 7.3.1 YouTube 추가 진행 상태', '#### 7.3.1 YouTube Add Progress State'),
    ('제출 후 즉시 완료되지 않고, 서버에서 스트림 준비 중. 클라이언트는 폴링으로 확인:',
     'Does not complete immediately after submission; server is preparing the stream. Client checks via polling:'),
    ('| 단계 | 표시 |', '| Stage | Display |'),
    ('| 시작 중 | `"스트림 시작 중… Xs"` (경과 시간 카운트) |', '| Starting | `"Starting stream… Xs"` (elapsed time count) |'),
    ('| `live` 상태 확인 | Modal 닫기 |', '| `live` status confirmed | Close Modal |'),
    ('| 오류 | 에러 메시지 표시 |', '| Error | Show error message |'),
    ('#### 7.3.2 YouTube 추가 에러 코드', '#### 7.3.2 YouTube Add Error Codes'),
    ('| 에러 코드 | 표시 메시지 |', '| Error code | Display message |'),
    ('| `INVALID_YOUTUBE_URL` | `유효하지 않은 YouTube URL입니다.` |',
     '| `INVALID_YOUTUBE_URL` | `Invalid YouTube URL.` |'),
    ('| `YT_DLP_FAILED` | `영상을 가져올 수 없습니다. 비공개 또는 삭제된 영상일 수 있습니다.` |',
     '| `YT_DLP_FAILED` | `Unable to retrieve video. It may be private or deleted.` |'),
    ('| `MAX_STREAMS_REACHED` | `YouTube 스트림 최대 개수에 도달했습니다.` |',
     '| `MAX_STREAMS_REACHED` | `Maximum number of YouTube streams reached.` |'),
    ('| `STREAM_TIMEOUT` | `스트림 시작 시간이 초과되었습니다. 다시 시도하세요.` |',
     '| `STREAM_TIMEOUT` | `Stream start timed out. Please try again.` |'),

    # Section 8
    ('## 8. 카메라 편집 Modal (CameraEditModal)', '## 8. Camera Edit Modal (CameraEditModal)'),
    ('카메라 행의 **✎(편집)** 버튼 또는 우클릭 메뉴로 진입. `z-50` 오버레이.',
     'Entered via the **✎ (edit)** button in the camera row or right-click menu. `z-50` overlay.'),
    ('### 8.1 RTSP 카메라 편집 폼', '### 8.1 RTSP Camera Edit Form'),
    ('| Name | text | 카메라 표시명 변경 |', '| Name | text | Change camera display name |'),
    ('| RTSP URL | text | 스트림 URL 변경 |', '| RTSP URL | text | Change stream URL |'),
    ('| Username | text | RTSP 인증 아이디 변경 |', '| Username | text | Change RTSP auth username |'),
    ('| Password | password | RTSP 인증 비밀번호 변경 (빈 값 = 변경 없음) |',
     '| Password | password | Change RTSP auth password (empty = no change) |'),
    ('| WebRTC Enabled | toggle | WebRTC 파이프라인 전환 |', '| WebRTC Enabled | toggle | Switch WebRTC pipeline |'),
    ('**저장 버튼 2종**:', '**Two save buttons**:'),
    ('| Save | `PUT /api/cameras/{id}` | 저장만 |', '| Save | `PUT /api/cameras/{id}` | Save only |'),
    ('| Save & Reconnect | `PUT /api/cameras/{id}` + `POST /api/cameras/{id}/stream/reconnect` | 저장 후 스트림 재연결 |',
     '| Save & Reconnect | `PUT /api/cameras/{id}` + `POST /api/cameras/{id}/stream/reconnect` | Save then reconnect stream |'),
    ('**WebRTC 변경 감지**: URL, 인증정보 변경 없이 `webrtcEnabled`만 변경된 경우, 서버에서 파이프라인 자동 재시작.',
     '**WebRTC change detection**: If only `webrtcEnabled` changes without URL or auth changes, the server auto-restarts the pipeline.'),
    ('### 8.2 YouTube 채널 편집 폼', '### 8.2 YouTube Channel Edit Form'),
    ('| Channel Name | text | 채널명 변경 |', '| Channel Name | text | Change channel name |'),
    ('| YouTube URL | text | URL 변경 (변경 시 스트림 재시작) |', '| YouTube URL | text | Change URL (stream restarts on change) |'),
    ('| Resolution | select | 해상도 변경 (변경 시 스트림 재시작) |', '| Resolution | select | Change resolution (stream restarts on change) |'),
    ('| Bitrate | number | 비트레이트 변경 (kbps) |', '| Bitrate | number | Change bitrate (kbps) |'),
    ('| 반복 재생 | checkbox | 영상 종료 시 자동 재시작 여부 (`repeatPlayback`) |',
     '| Repeat Playback | checkbox | Auto-restart when video ends (`repeatPlayback`) |'),
    ('### 8.3 저장 피드백', '### 8.3 Save Feedback'),
    ('| 저장 중 | `"Saving…"` (버튼 비활성화) |', '| Saving | `"Saving…"` (button disabled) |'),
    ('| 저장 성공 | `"Saved."` 또는 `"Saved & reconnecting…"` (0.8s 후 Modal 닫기) |',
     '| Save success | `"Saved."` or `"Saved & reconnecting…"` (Modal closes after 0.8s) |'),
    ('| 오류 | 빨간 에러 메시지 |', '| Error | Red error message |'),

    # Section 9
    ('## 9. Discovered Camera Panel (오버레이)', '## 9. Discovered Camera Panel (Overlay)'),
    ('Found 탭에서 탐색된 기기 클릭 시 Camera Grid 위에 오버레이로 표시.',
     'Displayed as an overlay above the Camera Grid when a device from the Found tab is clicked.'),
    ('### 9.1 위치', '### 9.1 Position'),
    ('- `absolute` (Camera Grid 영역 기준)', '- `absolute` (relative to Camera Grid area)'),
    ('- 위치: 우하단 또는 좌상단 (구현에 따라)', '- Position: bottom-right or top-left (depending on implementation)'),
    ('- 컴포넌트: `DiscoveredCameraPanel`', '- Component: `DiscoveredCameraPanel`'),
    ('### 9.2 표시 정보', '### 9.2 Displayed Information'),
    ('| 기기 이름 / 모델 | `Model` 또는 `IPAddress` |', '| Device name / model | `Model` or `IPAddress` |'),
    ('| 제조사 | `Manufacturer` |', '| Manufacturer | `Manufacturer` |'),
    ('| IP 주소 | `IPAddress` |', '| IP address | `IPAddress` |'),
    ('| MAC 주소 | `MACAddress` |', '| MAC address | `MACAddress` |'),
    ('| ONVIF / SUNAPI 지원 여부 | 뱃지 표시 |', '| ONVIF / SUNAPI support | Badge display |'),
    ('| 펌웨어 버전 | `FirmwareVersion` (있을 경우) |', '| Firmware version | `FirmwareVersion` (if present) |'),
    ('### 9.3 액션 버튼', '### 9.3 Action Buttons'),
    ('| **카메라로 추가** | 해당 기기 정보로 카메라 추가 Modal 자동 채움 후 열기 |',
     '| **Add as camera** | Auto-fill camera add Modal with device info and open |'),
    ('| **닫기** | `DiscoveryStore.select(null)` |', '| **Close** | `DiscoveryStore.select(null)` |'),

    # Section 10
    ('## 10. REST API 연동', '## 10. REST API Integration'),
    ('### 10.1 카메라 관련 API', '### 10.1 Camera-related APIs'),
    ('| 메서드 | 엔드포인트 | 설명 |', '| Method | Endpoint | Description |'),
    ('| `GET` | `/api/cameras` | 등록된 카메라 목록 조회 |', '| `GET` | `/api/cameras` | Get registered camera list |'),
    ('| `POST` | `/api/cameras` | 카메라 추가 |', '| `POST` | `/api/cameras` | Add camera |'),
    ('| `PUT` | `/api/cameras/:id` | 카메라 정보 수정 |', '| `PUT` | `/api/cameras/:id` | Update camera info |'),
    ('| `DELETE` | `/api/cameras/:id` | 카메라 삭제 |', '| `DELETE` | `/api/cameras/:id` | Delete camera |'),
    ('| `POST` | `/api/cameras/:id/stream/reconnect` | 스트림 재연결 |',
     '| `POST` | `/api/cameras/:id/stream/reconnect` | Reconnect stream |'),
    ('### 10.2 YouTube 스트림 API', '### 10.2 YouTube Stream API'),
    ('| `POST` | `/api/youtube-streams` | YouTube 채널 추가 시작 |', '| `POST` | `/api/youtube-streams` | Start adding YouTube channel |'),
    ('| `GET` | `/api/youtube-streams/:id/status` | 스트림 상태 폴링 |', '| `GET` | `/api/youtube-streams/:id/status` | Poll stream status |'),
    ('| `PATCH` | `/api/youtube-streams/:id` | YouTube 채널 정보 수정 |', '| `PATCH` | `/api/youtube-streams/:id` | Update YouTube channel info |'),
    ('| `POST` | `/api/youtube-streams/:id/restart` | 스트림 재시작 |', '| `POST` | `/api/youtube-streams/:id/restart` | Restart stream |'),
    ('### 10.3 카메라 추가 요청 Body', '### 10.3 Camera Add Request Body'),
    ('### 10.4 카메라 수정 요청 Body', '### 10.4 Camera Update Request Body'),

    # Section 11
    ('## 11. 상태 관리', '## 11. State Management'),
    ('### 11.1 CameraStore (Zustand)', '### 11.1 CameraStore (Zustand)'),
    ('| 상태 | 타입 | 설명 |', '| State | Type | Description |'),
    ('| `cameras` | `Camera[]` | 등록된 카메라 목록 |', '| `cameras` | `Camera[]` | Registered camera list |'),
    ('| `selectedId` | `string \\| null` | 현재 선택된 카메라 ID |', '| `selectedId` | `string \\| null` | Currently selected camera ID |'),
    ('| `setCameras(cameras)` | 전체 목록 설정 (서버 초기 로드 시) |',
     '| `setCameras(cameras)` | Set entire list (on initial server load) |'),
    ('| `addCamera(camera)` | 카메라 추가 |', '| `addCamera(camera)` | Add camera |'),
    ('| `updateCamera(id, fields)` | 카메라 정보 업데이트 |', '| `updateCamera(id, fields)` | Update camera info |'),
    ('| `removeCamera(id)` | 카메라 삭제 |', '| `removeCamera(id)` | Remove camera |'),
    ('| `updateCameraStatus(id, status)` | 상태 변경 |', '| `updateCameraStatus(id, status)` | Change status |'),
    ('| `selectCamera(id)` | 카메라 선택 |', '| `selectCamera(id)` | Select camera |'),
    ('### 11.2 DiscoveryStore (Zustand)', '### 11.2 DiscoveryStore (Zustand)'),
    ('| `cameras` | `DiscoveredCamera[]` | 탐색된 기기 목록 |', '| `cameras` | `DiscoveredCamera[]` | Discovered device list |'),
    ('| `selected` | `DiscoveredCamera \\| null` | 선택된 탐색 기기 |', '| `selected` | `DiscoveredCamera \\| null` | Selected discovered device |'),
    ('| `scanning` | `boolean` | 스캔 진행 중 여부 |', '| `scanning` | `boolean` | Whether scan is in progress |'),
    ('### 11.3 Socket.IO 이벤트', '### 11.3 Socket.IO Events'),
    ('| 이벤트 | 방향 | 처리 |', '| Event | Direction | Handler |'),
    ('| `cameras` | S→C | `setCameras()` |', '| `cameras` | S→C | `setCameras()` |'),
    ('| `camera:status` | S→C | `updateCameraStatus()` |', '| `camera:status` | S→C | `updateCameraStatus()` |'),
    ('| `discovery:result` | S→C | `addOrUpdate()` + 자동 탭 전환 |',
     '| `discovery:result` | S→C | `addOrUpdate()` + auto tab switch |'),
    ('| `discovery:scanning` | S→C | `setScanning()` |', '| `discovery:scanning` | S→C | `setScanning()` |'),
    ('| `discovery:cleared` | S→C | `clearFound()` |', '| `discovery:cleared` | S→C | `clearFound()` |'),
    ('| `discovery:rescan` | C→S | 스캔 초기화 및 재시작 요청 |',
     '| `discovery:rescan` | C→S | Request scan reset and restart |'),

    # Section 12
    ('## 12. 구현 현황', '## 12. Implementation Status'),
    ('### 12.1 Phase-1 완료 항목', '### 12.1 Phase-1 Completed Items'),
    ('| 항목 | 상태 |', '| Item | Status |'),
    ('| Added 탭 카메라 목록 | ✅ 완료 |', '| Added tab camera list | ✅ Done |'),
    ('| StatusDot 색상 5종 | ✅ 완료 |', '| StatusDot 5 colors | ✅ Done |'),
    ('| 카메라 행 액션 버튼 (편집/재연결/삭제) | ✅ 완료 |', '| Camera row action buttons (edit/reconnect/delete) | ✅ Done |'),
    ('| 더블클릭 재연결 | ✅ 완료 |', '| Double-click reconnect | ✅ Done |'),
    ('| YouTube 채널 YT 뱃지 | ✅ 완료 |', '| YouTube channel YT badge | ✅ Done |'),
    ('| 카메라 추가 Modal (RTSP) | ✅ 완료 |', '| Camera add Modal (RTSP) | ✅ Done |'),
    ('| 카메라 추가 Modal (YouTube) | ✅ 완료 |', '| Camera add Modal (YouTube) | ✅ Done |'),
    ('| YouTube 스트림 폴링 진행 상태 | ✅ 완료 |', '| YouTube stream polling progress state | ✅ Done |'),
    ('| 카메라 편집 Modal (RTSP/YouTube) | ✅ 완료 |', '| Camera edit Modal (RTSP/YouTube) | ✅ Done |'),
    ('| Found 탭 탐색 목록 | ✅ 완료 |', '| Found tab discovery list | ✅ Done |'),
    ('| Found 탭 검색 바 (문자열 + 카테고리) | ✅ 완료 |', '| Found tab search bar (string + category) | ✅ Done |'),
    ('| 자동 탭 전환 (첫 기기 발견 시) | ✅ 완료 |', '| Auto tab switch (on first device found) | ✅ Done |'),
    ('| Discovered Camera Panel 오버레이 | ✅ 완료 |', '| Discovered Camera Panel overlay | ✅ Done |'),
    ('| WebRTC Enabled 토글 (카메라별) | ✅ 완료 |', '| WebRTC Enabled toggle (per camera) | ✅ Done |'),
    ('### 12.2 미구현 / 개선 예정 항목', '### 12.2 Not Yet Implemented / Planned Improvements'),
    ('| 카메라 드래그&드롭 순서 변경 | 중 | |', '| Camera drag & drop reorder | Medium | |'),
    ('| 카메라 그룹/채널 구분 | 하 | |', '| Camera group/channel distinction | Low | |'),
    ('| RTSP URL 유효성 사전 검증 | 중 | |', '| RTSP URL pre-validation | Medium | |'),
    ('| 카메라 썸네일 미리보기 (목록 행 내) | 하 | |', '| Camera thumbnail preview (within list row) | Low | |'),
    ('| 다중 카메라 일괄 삭제 | 하 | |', '| Bulk delete multiple cameras | Low | |'),
    ('| ONVIF 인증 연동 (자동 RTSP URL 생성) | 중 | `DiscoveredCameraPanel` 통해 |',
     '| ONVIF auth integration (auto RTSP URL generation) | Medium | Via `DiscoveredCameraPanel` |'),
    ('| YouTube 실시간 채널 지원 | 하 | 현재 VOD/라이브 URL |',
     '| YouTube live channel support | Low | Currently VOD/live URL |'),
]

result = translate_file(f'{BASE}/RFP_Dashboard_Sidebar_Cameras.md', cameras_replacements)
print(f"RFP_Dashboard_Sidebar_Cameras.md: {'updated' if result else 'no changes'}")
print("Phase 2 part 3 complete.")
