import re

def translate_file(filepath, replacements):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    original = content
    for korean, english in replacements:
        content = content.replace(korean, english)
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False

BASE = '/home/youngho/workspace/loitering_tracking'

# ============================================================
# RFP_Dashboard_Sidebar_Alerts_Zones.md
# ============================================================
alerts_zones_replacements = [
    ('# RFP: Dashboard Sidebar — Alerts 및 Zones 패널',
     '# RFP: Dashboard Sidebar — Alerts and Zones Panel'),
    ('**Status**: Phase-1 구현 기준 작성', '**Status**: Written based on Phase-1 implementation'),

    ('## 목차', '## Table of Contents'),
    ('1. [개요](#1-개요)', '1. [Overview](#1-overview)'),
    ('2. [Alerts 패널 구성도](#2-alerts-패널-구성도)', '2. [Alerts Panel Diagram](#2-alerts-panel-diagram)'),
    ('3. [Alerts 패널 헤더](#3-alerts-패널-헤더)', '3. [Alerts Panel Header](#3-alerts-panel-header)'),
    ('4. [경보 행 (AlertRow)](#4-경보-행-alertrow)', '4. [Alert Row (AlertRow)](#4-alert-row-alertrow)'),
    ('5. [경보 빈 상태](#5-경보-빈-상태)', '5. [Alert Empty State](#5-alert-empty-state)'),
    ('6. [Alerts 데이터 모델](#6-alerts-데이터-모델)', '6. [Alerts Data Model](#6-alerts-data-model)'),
    ('7. [Zones 탭 구성](#7-zones-탭-구성)', '7. [Zones Tab Configuration](#7-zones-tab-configuration)'),
    ('8. [Zone Editor (전체화면 편집기)](#8-zone-editor-전체화면-편집기)', '8. [Zone Editor (Fullscreen Editor)](#8-zone-editor-fullscreen-editor)'),
    ('9. [Zone 데이터 모델](#9-zone-데이터-모델)', '9. [Zone Data Model](#9-zone-data-model)'),
    ('10. [Zone REST API](#10-zone-rest-api)', '10. [Zone REST API](#10-zone-rest-api)'),
    ('11. [Alerts REST API](#11-alerts-rest-api)', '11. [Alerts REST API](#11-alerts-rest-api)'),
    ('12. [상태 관리](#12-상태-관리)', '12. [State Management](#12-state-management)'),
    ('13. [구현 현황](#13-구현-현황)', '13. [Implementation Status](#13-implementation-status)'),

    # Section 1
    ('## 1. 개요', '## 1. Overview'),
    ('### 1.1 목적\n\n본 문서는 LTS Dashboard 우측 Sidebar의 **Alerts 탭** 패널 및 **Zones 탭** 패널에 대한 기술 요구사항을 정의한다.\n\n- **Alerts 패널**: Socket.IO로 수신되는 실시간 배회 경보(loitering alert)를 표시하고, 확인(acknowledge) 처리를 지원한다.\n- **Zones 탭**: 구역(Zone) 관리의 진입점을 제공하며, 실제 Zone 편집은 전체화면 카메라 뷰 위에서 `ZoneEditor` 컴포넌트를 통해 수행된다.',
     '### 1.1 Purpose\n\nThis document defines the technical requirements for the **Alerts tab** panel and **Zones tab** panel of the LTS Dashboard right sidebar.\n\n- **Alerts panel**: Displays real-time loitering alerts received via Socket.IO and supports acknowledge processing.\n- **Zones tab**: Provides an entry point for Zone management; actual Zone editing is performed via the `ZoneEditor` component over the fullscreen camera view.'),
    ('### 1.2 범위\n\n- Alerts 패널: 실시간 경보 목록, 미확인 카운트, 개별/일괄 확인, 빈 상태 UI\n- Zones 탭: 진입 가이드 힌트, Zone Editor 전체화면 진입 방법\n- Zone Editor: 폴리곤 그리기, 편집, 삭제, 속성 설정\n- Zone 데이터 타입 및 API 연동',
     '### 1.2 Scope\n\n- Alerts panel: Real-time alert list, unacknowledged count, individual/bulk acknowledge, empty state UI\n- Zones tab: Entry guide hint, Zone Editor fullscreen entry method\n- Zone Editor: Polygon drawing, editing, deletion, property setting\n- Zone data types and API integration'),

    # Section 2
    ('## 2. Alerts 패널 구성도', '## 2. Alerts Panel Diagram'),
    ('│  ┌──────────────────────────────┐│\n│  │ ⚠  CameraName      2m ago   ││  ← AlertRow (미확인)\n│  │    Obj #42 · Zone A         ││    배경: bg-red-950/20\n│  │    Dwell: 45.3s             ││    테두리: border-red-900/40\n│  │                       [Ack] ││\n│  └──────────────────────────────┘│\n│  ┌──────────────────────────────┐│\n│  │ ⚠  CameraName      5m ago   ││  ← AlertRow (확인됨)\n│  │    Obj #31 · Zone B         ││    배경: bg-gray-800\n│  │    Dwell: 32.1s             ││    투명도: opacity-60\n│  └──────────────────────────────┘│\n│  ...                             │\n│  (최대 20개 표시)                  │',
     '│  ┌──────────────────────────────┐│\n│  │ ⚠  CameraName      2m ago   ││  ← AlertRow (unacknowledged)\n│  │    Obj #42 · Zone A         ││    background: bg-red-950/20\n│  │    Dwell: 45.3s             ││    border: border-red-900/40\n│  │                       [Ack] ││\n│  └──────────────────────────────┘│\n│  ┌──────────────────────────────┐│\n│  │ ⚠  CameraName      5m ago   ││  ← AlertRow (acknowledged)\n│  │    Obj #31 · Zone B         ││    background: bg-gray-800\n│  │    Dwell: 32.1s             ││    opacity: opacity-60\n│  └──────────────────────────────┘│\n│  ...                             │\n│  (max 20 displayed)              │'),
    ('[경보 없을 때]\n┌──────────────────────────────────┐\n│  Alerts                          │\n├──────────────────────────────────┤\n│         ✓                        │\n│      (경보 없음 아이콘)            │\n│         No alerts                │\n└──────────────────────────────────┘',
     '[When no alerts]\n┌──────────────────────────────────┐\n│  Alerts                          │\n├──────────────────────────────────┤\n│         ✓                        │\n│      (no-alerts icon)            │\n│         No alerts                │\n└──────────────────────────────────┘'),

    # Section 3
    ('## 3. Alerts 패널 헤더', '## 3. Alerts Panel Header'),
    ('### 3.1 구성 요소', '### 3.1 Components'),
    ('```\n[Alerts 제목]  [미확인 수 뱃지]     [Clear All 버튼]\n```',
     '```\n[Alerts title]  [unacknowledged count badge]     [Clear All button]\n```'),
    ('| 요소 | 조건 | CSS |', '| Element | Condition | CSS |'),
    ('| **제목** | 항상 표시 | `text-sm font-bold text-white` |', '| **Title** | Always shown | `text-sm font-bold text-white` |'),
    ('| **미확인 수 뱃지** | `unacknowledged > 0`일 때만 | `text-[10px] font-bold bg-red-600 text-white rounded-full px-1.5 py-0.5 min-w-[20px] text-center` |',
     '| **Unacknowledged count badge** | Only when `unacknowledged > 0` | `text-[10px] font-bold bg-red-600 text-white rounded-full px-1.5 py-0.5 min-w-[20px] text-center` |'),
    ('| **Clear All 버튼** | `alerts.length > 0`일 때만 | `text-[11px] text-gray-400 hover:text-red-400` |',
     '| **Clear All button** | Only when `alerts.length > 0` | `text-[11px] text-gray-400 hover:text-red-400` |'),
    ('### 3.2 i18n 키', '### 3.2 i18n Keys'),
    ('| 키 | 영문 기본값 |', '| Key | English Default |'),
    ('### 3.3 Clear All 동작', '### 3.3 Clear All Behavior'),
    ('- `AlertStore.clearAlerts()` 호출', '- Calls `AlertStore.clearAlerts()`'),
    ('- REST API 호출 없이 클라이언트 스토어에서만 즉시 삭제', '- Immediately deleted from client store only, without REST API call'),
    ('- 서버 경보 이력은 유지됨', '- Server alert history is preserved'),

    # Section 4
    ('## 4. 경보 행 (AlertRow)', '## 4. Alert Row (AlertRow)'),
    ('### 4.1 행 구조', '### 4.1 Row Structure'),
    ('| 영역 | 요소 | 설명 |', '| Area | Element | Description |'),
    ('| 좌측 | 경보 아이콘 ⚠ | 미확인: `text-red-400`, 확인됨: `text-gray-500` |',
     '| Left | Alert icon ⚠ | Unacknowledged: `text-red-400`, Acknowledged: `text-gray-500` |'),
    ('| 중앙 상단 | 카메라 이름 | CameraStore에서 `alert.cameraId`로 조회. 없으면 ID 표시 |',
     '| Center top | Camera name | Looked up from CameraStore by `alert.cameraId`. Shows ID if not found |'),
    ('| 중앙 상단 우측 | 상대 시간 | `relativeTime(timestamp)` 함수 결과 |',
     '| Center top right | Relative time | Result of `relativeTime(timestamp)` function |'),
    ('| 중앙 중단 | 객체 번호 + 구역명 | `Obj #{objectId}` + `· {zone}` (구역 있을 경우) |',
     '| Center middle | Object number + zone name | `Obj #{objectId}` + `· {zone}` (if zone exists) |'),
    ('| 중앙 하단 | 드웰타임 | `Dwell: {dwellTime.toFixed(1)}s` |',
     '| Center bottom | Dwell time | `Dwell: {dwellTime.toFixed(1)}s` |'),
    ('| 우측 | Ack 버튼 | 미확인일 때만 표시 |', '| Right | Ack button | Shown only when unacknowledged |'),
    ('### 4.2 시간 표시 형식 (relativeTime)', '### 4.2 Time Display Format (relativeTime)'),
    ('| 경과 시간 | 표시 형식 |', '| Elapsed time | Display format |'),
    ('| < 60초 | `Ns ago` |', '| < 60s | `Ns ago` |'),
    ('| < 60분 | `Nm ago` |', '| < 60m | `Nm ago` |'),
    ('| 1시간 이상 | `Nh ago` |', '| 1h or more | `Nh ago` |'),
    ('### 4.3 미확인 경보 행 스타일', '### 4.3 Unacknowledged Alert Row Style'),
    ('### 4.4 확인된 경보 행 스타일', '### 4.4 Acknowledged Alert Row Style'),
    ('### 4.5 Ack (확인) 버튼', '### 4.5 Ack (Acknowledge) Button'),
    ('| 항목 | 값 |', '| Item | Value |'),
    ('| 표시 조건 | `!alert.acknowledged` |', '| Show condition | `!alert.acknowledged` |'),
    ('| 클릭 동작 | `POST /api/alerts/{id}/acknowledge` → 실패해도 `AlertStore.acknowledgeAlert(id)` 로컬 처리 |',
     '| Click behavior | `POST /api/alerts/{id}/acknowledge` → `AlertStore.acknowledgeAlert(id)` local processing even on failure |'),
    ('### 4.6 표시 제한', '### 4.6 Display Limit'),
    ('- 최대 표시: `MAX_VISIBLE = 20`개 (최신 순)', '- Maximum display: `MAX_VISIBLE = 20` items (newest first)'),
    ('- 나머지는 스크롤하지 않고 잘림 (20개 초과 분 미표시)', '- Remainder is truncated without scroll (items beyond 20 not shown)'),

    # Section 5
    ('## 5. 경보 빈 상태', '## 5. Alert Empty State'),
    ('경보가 없을 때 패널 중앙에 표시:', 'Displayed in the center of the panel when there are no alerts:'),
    ('- 아이콘: `path="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"` (체크 원)',
     '- Icon: `path="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"` (check circle)'),
    ('- 컨테이너: `flex flex-col items-center justify-center h-full text-gray-600 text-xs`',
     '- Container: `flex flex-col items-center justify-center h-full text-gray-600 text-xs`'),

    # Section 6
    ('## 6. Alerts 데이터 모델', '## 6. Alerts Data Model'),
    ('### 6.1 Alert 인터페이스', '### 6.1 Alert Interface'),
    ('  id: string;              // UUID', '  id: string;              // UUID'),
    ('  cameraId: string;        // 카메라 ID', '  cameraId: string;        // Camera ID'),
    ('  objectId: number;        // ByteTracker 객체 번호', '  objectId: number;        // ByteTracker object number'),
    ('  zone?: string;           // 트리거된 구역명 (없을 수도 있음)', '  zone?: string;           // Triggered zone name (may be absent)'),
    ('  dwellTime: number;       // 초 단위 드웰타임 (소수점 1자리)', '  dwellTime: number;       // Dwell time in seconds (1 decimal place)'),
    ('  timestamp: number;       // Unix 밀리초', '  timestamp: number;       // Unix milliseconds'),
    ('  acknowledged: boolean;   // 확인 여부', '  acknowledged: boolean;   // Whether acknowledged'),
    ('### 6.2 경보 발생 조건', '### 6.2 Alert Trigger Conditions'),
    ('| 조건 | 설명 |', '| Condition | Description |'),
    ('| Zone 내 객체 드웰타임 초과 | `dwellTime >= zone.dwellThreshold` |',
     '| Object dwell time exceeds threshold in zone | `dwellTime >= zone.dwellThreshold` |'),
    ('| Zone 내 최소 이동 거리 충족 | `displacement >= zone.minDisplacement` |',
     '| Minimum displacement reached in zone | `displacement >= zone.minDisplacement` |'),
    ('| 위험도 점수 초과 | `riskScore >= zone.minRiskScore` |', '| Risk score exceeded | `riskScore >= zone.minRiskScore` |'),
    ('| Zone 타입 | `MONITOR` 구역에서만 경보 발생 (`EXCLUDE` 제외) |',
     '| Zone type | Alert triggered only in `MONITOR` zones (excluding `EXCLUDE`) |'),
    ('### 6.3 Socket.IO 실시간 수신', '### 6.3 Socket.IO Real-time Reception'),

    # Section 7
    ('## 7. Zones 탭 구성', '## 7. Zones Tab Configuration'),
    ('### 7.1 Sidebar 내 Zones 탭 화면', '### 7.1 Zones Tab Screen in Sidebar'),
    ('Zones 탭 클릭 시 Sidebar 영역에 직접 Zone 편집 UI가 표시되지 않는다.  \n대신 **전체화면(Fullscreen) 모드에서만 Zone 편집**이 가능하다.  \nSidebar Zones 탭은 이 사실을 안내하는 힌트만 표시한다.',
     'Clicking the Zones tab does not display the Zone editing UI directly in the Sidebar area.  \nInstead, **Zone editing is only available in Fullscreen mode**.  \nThe Sidebar Zones tab only shows a hint explaining this.'),
    ('│         🗺 (지도 아이콘)           │', '│         🗺 (map icon)              │'),
    ('│  전체화면 카메라 뷰를 열어          │', '│  Open fullscreen camera view to    │'),
    ('│  감지 구역을 그리고 관리하세요       │', '│  draw and manage detection zones   │'),
    ('│  [카메라가 없을 경우 서브 힌트]     │', '│  [Sub-hint when no cameras]        │'),
    ('### 7.2 힌트 텍스트 i18n', '### 7.2 Hint Text i18n'),
    ('### 7.3 Zone 편집 진입 경로', '### 7.3 Zone Editing Entry Path'),
    ('```\nDashboard → Camera Grid 셀 더블클릭 \n  → FullscreenCameraView 열림\n  → 하단 "Zone Editor" 버튼 클릭\n  → ZoneEditor 전체화면 편집기 진입\n```',
     '```\nDashboard → Double-click Camera Grid cell\n  → FullscreenCameraView opens\n  → Click "Zone Editor" button at bottom\n  → Enter ZoneEditor fullscreen editor\n```'),

    # Section 8
    ('## 8. Zone Editor (전체화면 편집기)', '## 8. Zone Editor (Fullscreen Editor)'),
    ('### 8.1 개요', '### 8.1 Overview'),
    ('`ZoneEditor`는 `fixed inset-0 z-[100]` 오버레이로 렌더링된다.  \n카메라의 마지막 캡처 프레임을 배경으로, Canvas 레이어 위에서 폴리곤을 직접 그리고 편집한다.',
     '`ZoneEditor` is rendered as a `fixed inset-0 z-[100]` overlay.  \nPolygons are drawn and edited directly on the Canvas layer over the camera\'s last captured frame as background.'),
    ('### 8.2 전체 화면 구성도', '### 8.2 Full-Screen Layout Diagram'),
    ('│  배경 이미지 (JPEG 프레임)                                │  (w-64, 우측 고정)   │',
     '│  Background image (JPEG frame)                           │  (w-64, fixed right) │'),
    ('│         Canvas 레이어 (전체)                              ├─────────────────────┤',
     '│         Canvas layer (full)                               ├─────────────────────┤'),
    ('│  ┌──────────────────────┐                               │  [선택 구역 속성]    │',
     '│  ┌──────────────────────┐                               │  [Selected zone props] │'),
    ('│  │  MONITOR 구역 (파랑)  │                               │  또는               │',
     '│  │  MONITOR zone (blue)  │                               │  or                 │'),
    ('│  │  (반투명 채움)         │                               │  [그리기 설정]       │',
     '│  │  (semi-transparent fill) │                            │  [Draw settings]    │'),
    ('│  ┌──────────────────────┐                               │  Saved Zones 목록    │',
     '│  ┌──────────────────────┐                               │  Saved Zones list   │'),
    ('│  │  EXCLUDE 구역 (노랑)  │                               └─────────────────────┘',
     '│  │  EXCLUDE zone (yellow) │                              └─────────────────────┘'),
    ('### 8.3 컨트롤 패널 구성 (우측 w-64)', '### 8.3 Control Panel Layout (right w-64)'),
    ('#### 8.3.1 헤더', '#### 8.3.1 Header'),
    ('| 제목 | `Zone Edit` (i18n: `zoneEdit`) |', '| Title | `Zone Edit` (i18n: `zoneEdit`) |'),
    ('| × 버튼 | ZoneEditor 종료 → FullscreenCameraView 복귀 |',
     '| × button | Exit ZoneEditor → return to FullscreenCameraView |'),
    ('#### 8.3.2 모드 탭 버튼', '#### 8.3.2 Mode Tab Buttons'),
    ('| 모드 | 버튼 텍스트 | 활성 스타일 |', '| Mode | Button Text | Active Style |'),
    ('| `idle` | `Select / Edit` | `bg-gray-700 text-white` |',
     '| `idle` | `Select / Edit` | `bg-gray-700 text-white` |'),
    ('| `draw` | `+ Add Zone` (i18n: `zoneAdd`) | `bg-blue-800 text-white` |',
     '| `draw` | `+ Add Zone` (i18n: `zoneAdd`) | `bg-blue-800 text-white` |'),
    ('### 8.4 Idle 모드 (Select / Edit)', '### 8.4 Idle Mode (Select / Edit)'),
    ('#### 8.4.1 구역 선택됨 — 속성 패널', '#### 8.4.1 Zone Selected — Properties Panel'),
    ('| 구역 이름 | text input | `onBlur` + `Enter` 키 → `PUT /api/cameras/{id}/zones/{zoneId}` |',
     '| Zone name | text input | `onBlur` + `Enter` key → `PUT /api/cameras/{id}/zones/{zoneId}` |'),
    ('| 구역 타입 | 뱃지 표시 (`MONITOR` 파랑, `EXCLUDE` 노랑) | 편집 불가 |',
     '| Zone type | Badge display (`MONITOR` blue, `EXCLUDE` yellow) | Not editable |'),
    ('| 버텍스 수 | 읽기 전용 텍스트 | |', '| Vertex count | Read-only text | |'),
    ('| Deselect 버튼 | — | 선택 해제 |', '| Deselect button | — | Deselect zone |'),
    ('| Save Polygon 버튼 | — | 편집된 폴리곤 저장 (`PUT` API) |',
     '| Save Polygon button | — | Save edited polygon (`PUT` API) |'),
    ('#### 8.4.2 구역 선택 안 됨 — 힌트', '#### 8.4.2 No Zone Selected — Hint'),
    ('```\n클릭하여 구역을 선택하세요\n(i18n: zoneClickToSelect)\n```',
     '```\nClick to select a zone\n(i18n: zoneClickToSelect)\n```'),
    ('### 8.5 Draw 모드 (+ Add Zone)', '### 8.5 Draw Mode (+ Add Zone)'),
    ('#### 8.5.1 그리기 설정 폼', '#### 8.5.1 Drawing Settings Form'),
    ('| 필드 | 타입 | 범위/옵션 | 기본값 | 설명 |', '| Field | Type | Range/Options | Default | Description |'),
    ('| 구역 이름 | text | — | `"Zone N"` | 저장될 구역명 |', '| Zone name | text | — | `"Zone N"` | Zone name to be saved |'),
    ('| 구역 타입 | 버튼 선택 | `MONITOR` / `EXCLUDE` | `MONITOR` | 배회 감지 vs 제외 |',
     '| Zone type | Button select | `MONITOR` / `EXCLUDE` | `MONITOR` | Loitering detection vs exclusion |'),
    ('| Dwell Threshold | range slider | 5–300초 | 30초 | 경보 발생 최소 드웰타임 |',
     '| Dwell Threshold | range slider | 5–300s | 30s | Minimum dwell time for alert trigger |'),
    ('| Min Displacement | range slider | 10–200px | 50px | 최소 이동 거리 |',
     '| Min Displacement | range slider | 10–200px | 50px | Minimum movement distance |'),
    ('| Min Risk Score | range slider | 0.00–1.00 (step 0.05) | 0.00 | 최소 위험도 점수 (0 = 비활성) |',
     '| Min Risk Score | range slider | 0.00–1.00 (step 0.05) | 0.00 | Minimum risk score (0 = inactive) |'),
    ('> `Dwell Threshold`, `Min Displacement`, `Min Risk Score`는 `MONITOR` 타입에서만 표시',
     '> `Dwell Threshold`, `Min Displacement`, `Min Risk Score` are only shown for `MONITOR` type'),
    ('#### 8.5.2 그리기 힌트', '#### 8.5.2 Drawing Hints'),
    ('| 상태 | 힌트 메시지 (i18n) |', '| State | Hint Message (i18n) |'),
    ('| 버텍스 0–2개 | `zoneDrawHint` (Canvas에 표시) |', '| 0–2 vertices | `zoneDrawHint` (shown on Canvas) |'),
    ('| 버텍스 3개 이상 | `zoneCanSave` 텍스트 표시 |', '| 3 or more vertices | `zoneCanSave` text shown |'),
    ('#### 8.5.3 저장/초기화 버튼', '#### 8.5.3 Save/Reset Buttons'),
    ('| 버튼 | 조건 | 동작 |', '| Button | Condition | Behavior |'),
    ('| Reset | 항상 | `drawPoints = []` |', '| Reset | Always | `drawPoints = []` |'),
    ('| Save | `drawPoints.length >= 3` | `POST /api/cameras/{id}/zones` |',
     '| Save | `drawPoints.length >= 3` | `POST /api/cameras/{id}/zones` |'),
    ('#### 8.5.4 그리기 완료 조건', '#### 8.5.4 Drawing Completion Conditions'),
    ('- 버텍스 최소 3개', '- Minimum 3 vertices'),
    ('- 구역 이름 비어있지 않아야 함', '- Zone name must not be empty'),
    ('### 8.6 Canvas 편집 상호작용', '### 8.6 Canvas Edit Interactions'),
    ('#### 8.6.1 구역 폴리곤 렌더링', '#### 8.6.1 Zone Polygon Rendering'),
    ('| 구역 타입 | 선 색상 | 채움 (기본) | 채움 (선택됨) |', '| Zone type | Line color | Fill (default) | Fill (selected) |'),
    ('#### 8.6.2 버텍스 렌더링', '#### 8.6.2 Vertex Rendering'),
    ('| 버텍스 원 | 반지름 6px, 구역 색상 채움 + 흰 테두리 |', '| Vertex circle | radius 6px, zone color fill + white border |'),
    ('| 선택된 버텍스 | 노란 강조 원 |', '| Selected vertex | Yellow highlight circle |'),
    ('| 커서 (드래그 중) | `grabbing` |', '| Cursor (dragging) | `grabbing` |'),
    ('| 커서 (버텍스 위) | `grab` |', '| Cursor (over vertex) | `grab` |'),
    ('| 커서 (그리기 모드) | `crosshair` |', '| Cursor (draw mode) | `crosshair` |'),
    ('#### 8.6.3 마우스 이벤트', '#### 8.6.3 Mouse Events'),
    ('| Click (draw 모드) | 버텍스 추가 |', '| Click (draw mode) | Add vertex |'),
    ('| Click (idle, 구역 위) | 구역 선택 |', '| Click (idle, over zone) | Select zone |'),
    ('| Click (idle, 버텍스 위) | 버텍스 선택 → 다음 클릭 위치로 이동 |',
     '| Click (idle, over vertex) | Select vertex → move to next click position |'),
    ('| Double Click | 버텍스 이동 완료 후 저장 |', '| Double Click | Save after vertex move complete |'),
    ('| Right Click | 컨텍스트 메뉴 표시 |', '| Right Click | Show context menu |'),
    ('| Drag (버텍스) | 드래그로 버텍스 위치 실시간 변경 |', '| Drag (vertex) | Real-time vertex position change via drag |'),
    ('#### 8.6.4 컨텍스트 메뉴 (우클릭)', '#### 8.6.4 Context Menu (Right-click)'),
    ('| Delete Zone | 구역 선택됨 | `DELETE /api/cameras/{id}/zones/{zoneId}` |',
     '| Delete Zone | Zone selected | `DELETE /api/cameras/{id}/zones/{zoneId}` |'),
    ('| Delete Vertex | 버텍스 선택됨 + 버텍스 4개 이상 | 해당 버텍스 제거 + 폴리곤 자동 저장 |',
     '| Delete Vertex | Vertex selected + 4 or more vertices | Remove vertex + auto-save polygon |'),
    ('### 8.7 Saved Zones 목록', '### 8.7 Saved Zones List'),
    ('컨트롤 패널 하단에 현재 카메라의 저장된 구역 목록 표시:', 'Displays the saved zone list for the current camera at the bottom of the control panel:'),
    ('| 색상 점 | MONITOR=파랑, EXCLUDE=노랑 |', '| Color dot | MONITOR=blue, EXCLUDE=yellow |'),
    ('| 이름 | 구역명 (truncate) |', '| Name | Zone name (truncate) |'),
    ('| 우측 텍스트 | MONITOR: `{dwellThreshold}s`, EXCLUDE: `EXCLUDE` |',
     '| Right text | MONITOR: `{dwellThreshold}s`, EXCLUDE: `EXCLUDE` |'),
    ('| targetClasses 약어 | 대상 클래스 있을 경우 파란 약어 표시 |',
     '| targetClasses abbreviation | Blue abbreviation shown if target classes exist |'),
    ('| ✕ 버튼 | 구역 삭제 (`DELETE` API) |', '| ✕ button | Delete zone (`DELETE` API) |'),

    # Section 9
    ('## 9. Zone 데이터 모델', '## 9. Zone Data Model'),
    ('### 9.1 Zone 인터페이스', '### 9.1 Zone Interface'),
    ('  id: string;                             // UUID', '  id: string;                             // UUID'),
    ('  cameraId: string;                       // 소속 카메라 ID', '  cameraId: string;                       // Camera ID this zone belongs to'),
    ('  name: string;                           // 구역명', '  name: string;                           // Zone name'),
    ('  type: \'MONITOR\' | \'EXCLUDE\';           // 구역 타입', '  type: \'MONITOR\' | \'EXCLUDE\';           // Zone type'),
    ('  polygon: Array<{ x: number; y: number }>; // 폴리곤 버텍스 목록 (프레임 좌표계)',
     '  polygon: Array<{ x: number; y: number }>; // Polygon vertex list (frame coordinate system)'),
    ('  dwellThreshold?: number;                // 드웰타임 임계값 (초, MONITOR)',
     '  dwellThreshold?: number;                // Dwell time threshold (seconds, MONITOR)'),
    ('  minDisplacement?: number;               // 최소 이동 거리 (px, MONITOR)',
     '  minDisplacement?: number;               // Minimum movement distance (px, MONITOR)'),
    ('  reentryWindow?: number;                 // 재진입 허용 윈도우 (초)',
     '  reentryWindow?: number;                 // Re-entry allowed window (seconds)'),
    ('  minRiskScore?: number;                  // 최소 위험도 점수 (0–1, MONITOR)',
     '  minRiskScore?: number;                  // Minimum risk score (0–1, MONITOR)'),
    ('  active?: boolean;                       // 활성 여부', '  active?: boolean;                       // Whether active'),
    ('  targetClasses?: string[];               // 감지 대상 클래스 필터', '  targetClasses?: string[];               // Detection target class filter'),
    ('### 9.2 구역 타입 정의', '### 9.2 Zone Type Definitions'),
    ('| 타입 | 색상 | 설명 |', '| Type | Color | Description |'),
    ('| `MONITOR` | 파랑 `#3b82f6` | 배회 감지 대상 구역. 드웰타임 초과 시 경보 발생 |',
     '| `MONITOR` | Blue `#3b82f6` | Zone subject to loitering detection. Alert triggered when dwell time exceeded |'),
    ('| `EXCLUDE` | 노랑 `#f59e0b` | 감지 제외 구역. 해당 구역 내 객체는 배회 판정에서 제외 |',
     '| `EXCLUDE` | Yellow `#f59e0b` | Detection exclusion zone. Objects within this zone are excluded from loitering judgment |'),
    ('### 9.3 좌표계', '### 9.3 Coordinate System'),
    ('폴리곤 좌표는 **프레임 좌표계** 기준 (px):\n- 원점: 프레임 좌상단 `(0, 0)`\n- 범위: `0 ≤ x ≤ frameWidth`, `0 ≤ y ≤ frameHeight`\n- 서버는 전송된 절대 px 좌표를 그대로 저장하고 BehaviorEngine에서 사용',
     'Polygon coordinates are based on the **frame coordinate system** (px):\n- Origin: top-left of frame `(0, 0)`\n- Range: `0 ≤ x ≤ frameWidth`, `0 ≤ y ≤ frameHeight`\n- Server stores the transmitted absolute px coordinates as-is and uses them in BehaviorEngine'),
    ('### 9.4 기본값', '### 9.4 Default Values'),
    ('| 속성 | 기본값 | 비고 |', '| Property | Default | Notes |'),
    ('| `dwellThreshold` | `30` (초) | 슬라이더 범위: 5–300 |', '| `dwellThreshold` | `30` (s) | Slider range: 5–300 |'),
    ('| `minDisplacement` | `50` (px) | 슬라이더 범위: 10–200 |', '| `minDisplacement` | `50` (px) | Slider range: 10–200 |'),
    ('| `minRiskScore` | `0.0` | 0이면 비활성 (위험도 필터 없음) |', '| `minRiskScore` | `0.0` | 0 = inactive (no risk filter) |'),

    # Section 10
    ('## 10. Zone REST API', '## 10. Zone REST API'),
    ('### 10.1 엔드포인트 목록', '### 10.1 Endpoint List'),
    ('| 메서드 | 엔드포인트 | 설명 |', '| Method | Endpoint | Description |'),
    ('| `GET` | `/api/cameras/:cameraId/zones` | 해당 카메라의 모든 구역 조회 |',
     '| `GET` | `/api/cameras/:cameraId/zones` | Get all zones for the camera |'),
    ('| `POST` | `/api/cameras/:cameraId/zones` | 새 구역 생성 |',
     '| `POST` | `/api/cameras/:cameraId/zones` | Create new zone |'),
    ('| `PUT` | `/api/cameras/:cameraId/zones/:zoneId` | 구역 수정 (name, polygon, 속성) |',
     '| `PUT` | `/api/cameras/:cameraId/zones/:zoneId` | Update zone (name, polygon, properties) |'),
    ('| `DELETE` | `/api/cameras/:cameraId/zones/:zoneId` | 구역 삭제 |',
     '| `DELETE` | `/api/cameras/:cameraId/zones/:zoneId` | Delete zone |'),
    ('### 10.2 구역 생성 요청 Body', '### 10.2 Zone Creation Request Body'),
    ('### 10.3 구역 수정 요청 Body (부분 업데이트)', '### 10.3 Zone Update Request Body (partial update)'),
    ('### 10.4 응답 형식', '### 10.4 Response Format'),

    # Section 11
    ('## 11. Alerts REST API', '## 11. Alerts REST API'),
    ('| `GET` | `/api/alerts` | 경보 목록 조회 |', '| `GET` | `/api/alerts` | Get alert list |'),
    ('| `POST` | `/api/alerts/:id/acknowledge` | 경보 확인 처리 |',
     '| `POST` | `/api/alerts/:id/acknowledge` | Acknowledge alert |'),
    ('### 11.2 경보 확인 응답', '### 11.2 Alert Acknowledgment Response'),
    ('오류 발생 시에도 클라이언트는 `AlertStore.acknowledgeAlert(id)`를 호출하여 로컬에서 즉시 처리한다. 이를 통해 서버 오류 시에도 UI가 반응성을 유지한다.',
     'Even on error, the client calls `AlertStore.acknowledgeAlert(id)` for immediate local processing. This ensures the UI remains responsive even when the server encounters an error.'),

    # Section 12
    ('## 12. 상태 관리', '## 12. State Management'),
    ('### 12.1 AlertStore (Zustand)', '### 12.1 AlertStore (Zustand)'),
    ('| 상태 | 타입 | 설명 |', '| State | Type | Description |'),
    ('| `alerts` | `Alert[]` | 경보 목록 (최신 순) |', '| `alerts` | `Alert[]` | Alert list (newest first) |'),
    ('| 액션 | 설명 |', '| Action | Description |'),
    ('| `addAlert(alert)` | 경보 추가 (맨 앞에 삽입) |', '| `addAlert(alert)` | Add alert (insert at front) |'),
    ('| `acknowledgeAlert(id)` | 해당 경보를 `acknowledged: true`로 변경 |',
     '| `acknowledgeAlert(id)` | Set alert `acknowledged: true` |'),
    ('| `clearAlerts()` | 전체 경보 목록 초기화 |', '| `clearAlerts()` | Clear entire alert list |'),
    ('### 12.2 Socket.IO 이벤트', '### 12.2 Socket.IO Events'),
    ('| `alert` | S→C | `AlertStore.addAlert()` |', '| `alert` | S→C | `AlertStore.addAlert()` |'),
    ('| `loitering` | S→C | FullscreenCameraView에서 처리 (Canvas 오버레이) |',
     '| `loitering` | S→C | Handled in FullscreenCameraView (Canvas overlay) |'),
    ('### 12.3 Zone 상태 관리', '### 12.3 Zone State Management'),
    ('Zone 데이터는 Zustand 전역 스토어 없이 **FullscreenCameraView 컴포넌트의 로컬 state**로 관리된다.',
     'Zone data is managed as **local state of the FullscreenCameraView component**, without a Zustand global store.'),
    ('| **초기 로드** | `GET /api/cameras/{id}/zones` — FullscreenCameraView 마운트 시 |',
     '| **Initial load** | `GET /api/cameras/{id}/zones` — when FullscreenCameraView mounts |'),
    ('| **생성** | `onZoneAdded(zone)` 콜백 → 로컬 state에 추가 |',
     '| **Create** | `onZoneAdded(zone)` callback → add to local state |'),
    ('| **수정** | `onZoneUpdated(zone)` 콜백 → 로컬 state 업데이트 |',
     '| **Update** | `onZoneUpdated(zone)` callback → update local state |'),
    ('| **삭제** | `onZoneDeleted(zoneId)` 콜백 → 로컬 state에서 제거 |',
     '| **Delete** | `onZoneDeleted(zoneId)` callback → remove from local state |'),

    # Section 13
    ('## 13. 구현 현황', '## 13. Implementation Status'),
    ('### 13.1 Alerts 패널 — Phase-1 완료 항목', '### 13.1 Alerts Panel — Phase-1 Completed Items'),
    ('| 항목 | 상태 |', '| Item | Status |'),
    ('| 실시간 경보 수신 (Socket.IO `alert`) | ✅ 완료 |', '| Real-time alert reception (Socket.IO `alert`) | ✅ Done |'),
    ('| AlertRow 구조 (아이콘, 카메라명, 시간, 객체번호, 구역, 드웰) | ✅ 완료 |',
     '| AlertRow structure (icon, camera name, time, object number, zone, dwell) | ✅ Done |'),
    ('| 미확인/확인 스타일 구분 | ✅ 완료 |', '| Unacknowledged/acknowledged style distinction | ✅ Done |'),
    ('| 상대 시간 표시 (Xs/Nm/Nh ago) | ✅ 완료 |', '| Relative time display (Xs/Nm/Nh ago) | ✅ Done |'),
    ('| Ack 버튼 (POST + 로컬 처리) | ✅ 완료 |', '| Ack button (POST + local processing) | ✅ Done |'),
    ('| 미확인 수 뱃지 (Sidebar 탭 및 패널 헤더) | ✅ 완료 |',
     '| Unacknowledged count badge (Sidebar tab and panel header) | ✅ Done |'),
    ('| 빈 상태 체크 아이콘 | ✅ 완료 |', '| Empty state check icon | ✅ Done |'),
    ('| 최대 20개 표시 제한 | ✅ 완료 |', '| Maximum 20 display limit | ✅ Done |'),
    ('| 다국어 (alertTitle, alertAckAll, noAlerts) | ✅ 완료 |', '| Multilingual (alertTitle, alertAckAll, noAlerts) | ✅ Done |'),
    ('### 13.2 Zones 탭 — Phase-1 완료 항목', '### 13.2 Zones Tab — Phase-1 Completed Items'),
    ('| Sidebar Zones 탭 힌트 화면 | ✅ 완료 |', '| Sidebar Zones tab hint screen | ✅ Done |'),
    ('| ZoneEditor 전체화면 편집기 | ✅ 완료 |', '| ZoneEditor fullscreen editor | ✅ Done |'),
    ('| MONITOR / EXCLUDE 타입 구분 | ✅ 완료 |', '| MONITOR / EXCLUDE type distinction | ✅ Done |'),
    ('| 폴리곤 그리기 (draw 모드) | ✅ 완료 |', '| Polygon drawing (draw mode) | ✅ Done |'),
    ('| 폴리곤 선택/편집/저장 (idle 모드) | ✅ 완료 |', '| Polygon select/edit/save (idle mode) | ✅ Done |'),
    ('| 버텍스 드래그 이동 | ✅ 완료 |', '| Vertex drag move | ✅ Done |'),
    ('| 버텍스 삭제 (우클릭 컨텍스트 메뉴) | ✅ 완료 |', '| Vertex delete (right-click context menu) | ✅ Done |'),
    ('| 구역 삭제 (우클릭 / 목록 ✕ 버튼) | ✅ 완료 |', '| Zone delete (right-click / list ✕ button) | ✅ Done |'),
    ('| Dwell Threshold 슬라이더 (5–300s) | ✅ 완료 |', '| Dwell Threshold slider (5–300s) | ✅ Done |'),
    ('| Min Displacement 슬라이더 | ✅ 완료 |', '| Min Displacement slider | ✅ Done |'),
    ('| Min Risk Score 슬라이더 | ✅ 완료 |', '| Min Risk Score slider | ✅ Done |'),
    ('| REST API 연동 (CRUD) | ✅ 완료 |', '| REST API integration (CRUD) | ✅ Done |'),
    ('| 배경 이미지 (마지막 JPEG 프레임) | ✅ 완료 |', '| Background image (last JPEG frame) | ✅ Done |'),
    ('| Canvas 좌표계 변환 (프레임↔캔버스) | ✅ 완료 |', '| Canvas coordinate conversion (frame↔canvas) | ✅ Done |'),
    ('### 13.3 미구현 / 개선 예정 항목', '### 13.3 Not Yet Implemented / Planned Improvements'),
    ('| 경보 필터링 (카메라별, 구역별, 날짜) | 중 | |', '| Alert filtering (by camera, zone, date) | Medium | |'),
    ('| 경보 음향 알림 | 중 | `AudioContext` 사용 |', '| Alert audio notification | Medium | Use `AudioContext` |'),
    ('| 경보 팝업 토스트 | 중 | |', '| Alert popup toast | Medium | |'),
    ('| 경보 영구 저장 및 이력 조회 | 높음 | DB 기반 이력 관리 |',
     '| Alert permanent storage and history query | High | DB-based history management |'),
    ('| Zone targetClasses UI 편집 | 중 | 현재 API에만 존재 |',
     '| Zone targetClasses UI editing | Medium | Currently API-only |'),
    ('| Zone reentryWindow 설정 UI | 하 | |', '| Zone reentryWindow settings UI | Low | |'),
    ('| Zones 탭에서 직접 Zone 목록 조회 | 중 | 현재 Fullscreen에서만 가능 |',
     '| Direct Zone list query from Zones tab | Medium | Currently only available in Fullscreen |'),
    ('| 다중 카메라 Zone 일괄 복사 | 하 | |', '| Bulk Zone copy across multiple cameras | Low | |'),
    ('| Zone 통계 (진입 횟수, 평균 드웰) | 하 | |', '| Zone statistics (entry count, average dwell) | Low | |'),
    ('| 경보 초당 발생 제한 (rate-limit UI 표시) | 중 | |',
     '| Alert rate limit per second (rate-limit UI display) | Medium | |'),
]

result = translate_file(f'{BASE}/RFP_Dashboard_Sidebar_Alerts_Zones.md', alerts_zones_replacements)
print(f"RFP_Dashboard_Sidebar_Alerts_Zones.md: {'updated' if result else 'no changes'}")

print("Phase 2 part 2 complete.")
